<?xml version="1.0" encoding="UTF-8"?>
<i18nResource xmlns="com.kingdee.bos.metadata">
    <package>com.kingdee.eas.custom.dx.baseset.client</package>
    <name>BasesetResource</name>
    <alias>i18nResource[com.kingdee.eas.custom.dx.baseset.client.BasesetResource].alias</alias>
    <description>i18nResource[com.kingdee.eas.custom.dx.baseset.client.BasesetResource].description</description>
    <userDefined>true</userDefined>
    <className>com.kingdee.eas.custom.dx.baseset.client.BasesetResource</className>
    <resourceItems>
        <resourceItem>
            <name>OtherGroupSetQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.dx.baseset.client.BasesetResource].resourceItems.resourceItem[OtherGroupSetQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>FoodDailyQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.dx.baseset.client.BasesetResource].resourceItems.resourceItem[FoodDailyQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>PackbasicQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.dx.baseset.client.BasesetResource].resourceItems.resourceItem[PackbasicQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>ChangepackingQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.dx.baseset.client.BasesetResource].resourceItems.resourceItem[ChangepackingQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
    </resourceItems>
    <resource>
        <rs key="i18nResource[com.kingdee.eas.custom.dx.baseset.client.BasesetResource].alias">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.dx.baseset.client.BasesetResource].description">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.dx.baseset.client.BasesetResource].resourceItems.resourceItem[ChangepackingQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="包装换算关系" />
            <lang locale="zh_HK" value="包裝換算關係" />
            <lang locale="zh_TW" value="包裝換算關係" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.dx.baseset.client.BasesetResource].resourceItems.resourceItem[FoodDailyQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="食品经营日报" />
            <lang locale="zh_HK" value="食品經營日報" />
            <lang locale="zh_TW" value="食品經營日報" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.dx.baseset.client.BasesetResource].resourceItems.resourceItem[OtherGroupSetQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="车间物料分类对应设置" />
            <lang locale="zh_HK" value="車間物料分類對應設置" />
            <lang locale="zh_TW" value="車間物料分類對應設置" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.dx.baseset.client.BasesetResource].resourceItems.resourceItem[PackbasicQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="包装信息维护" />
            <lang locale="zh_HK" value="包裝信息維護" />
            <lang locale="zh_TW" value="包裝信息維護" />
        </rs>
    </resource>
</i18nResource>

