<?xml version="1.0" encoding="UTF-8"?>
<i18nResource xmlns="com.kingdee.bos.metadata">
    <package>com.kingdee.eas.farm.stocking.rpt.client</package>
    <name>RptResource</name>
    <alias>i18nResource[com.kingdee.eas.farm.stocking.rpt.client.RptResource].alias</alias>
    <description>i18nResource[com.kingdee.eas.farm.stocking.rpt.client.RptResource].description</description>
    <userDefined>true</userDefined>
    <className>com.kingdee.eas.farm.stocking.rpt.client.RptResource</className>
    <resourceItems>
        <resourceItem>
            <name>QwerQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.stocking.rpt.client.RptResource].resourceItems.resourceItem[QwerQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
    </resourceItems>
    <resource>
        <rs key="i18nResource[com.kingdee.eas.farm.stocking.rpt.client.RptResource].alias">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.stocking.rpt.client.RptResource].description">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.stocking.rpt.client.RptResource].resourceItems.resourceItem[QwerQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="测试控件" />
            <lang locale="zh_TW" value="null" />
        </rs>
    </resource>
</i18nResource>

