<?xml version="1.0" encoding="UTF-8"?>
<i18nResource xmlns="com.kingdee.bos.metadata">
    <package>com.kingdee.eas.wlhlcomm.client</package>
    <name>WlhlcommResource</name>
    <alias>i18nResource[com.kingdee.eas.wlhlcomm.client.WlhlcommResource].alias</alias>
    <description>i18nResource[com.kingdee.eas.wlhlcomm.client.WlhlcommResource].description</description>
    <userDefined>true</userDefined>
    <className>com.kingdee.eas.wlhlcomm.client.WlhlcommResource</className>
    <resourceItems>
        <resourceItem>
            <name>ErQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.wlhlcomm.client.WlhlcommResource].resourceItems.resourceItem[ErQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>BillUpdateLogQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.wlhlcomm.client.WlhlcommResource].resourceItems.resourceItem[BillUpdateLogQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>TobeUpdateBillsQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.wlhlcomm.client.WlhlcommResource].resourceItems.resourceItem[TobeUpdateBillsQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
    </resourceItems>
    <resource>
        <rs key="i18nResource[com.kingdee.eas.wlhlcomm.client.WlhlcommResource].alias">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.wlhlcomm.client.WlhlcommResource].description">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.wlhlcomm.client.WlhlcommResource].resourceItems.resourceItem[BillUpdateLogQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="单据更新记录" />
            <lang locale="zh_HK" value="單據更新記錄" />
            <lang locale="zh_TW" value="單據更新記錄" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.wlhlcomm.client.WlhlcommResource].resourceItems.resourceItem[ErQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="Er" />
            <lang locale="zh_HK" value="Er" />
            <lang locale="zh_TW" value="Er" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.wlhlcomm.client.WlhlcommResource].resourceItems.resourceItem[TobeUpdateBillsQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="需要更新单据" />
            <lang locale="zh_HK" value="需要更新單據" />
            <lang locale="zh_TW" value="需要更新單據" />
        </rs>
    </resource>
</i18nResource>

