<?xml version="1.0" encoding="UTF-8"?>
<i18nResource xmlns="com.kingdee.bos.metadata">
    <package>com.kingdee.eas.custom.eas2wincos.client</package>
    <name>Eas2wincosResource</name>
    <alias>i18nResource[com.kingdee.eas.custom.eas2wincos.client.Eas2wincosResource].alias</alias>
    <description>i18nResource[com.kingdee.eas.custom.eas2wincos.client.Eas2wincosResource].description</description>
    <userDefined>true</userDefined>
    <className>com.kingdee.eas.custom.eas2wincos.client.Eas2wincosResource</className>
    <resourceItems>
        <resourceItem>
            <name>DataBaseSettingQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.eas2wincos.client.Eas2wincosResource].resourceItems.resourceItem[DataBaseSettingQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>JhdlaQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.eas2wincos.client.Eas2wincosResource].resourceItems.resourceItem[JhdlaQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
    </resourceItems>
    <resource>
        <rs key="i18nResource[com.kingdee.eas.custom.eas2wincos.client.Eas2wincosResource].alias">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.eas2wincos.client.Eas2wincosResource].description">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.eas2wincos.client.Eas2wincosResource].resourceItems.resourceItem[DataBaseSettingQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="中间库连接设置" />
            <lang locale="zh_HK" value="中間庫連接設置" />
            <lang locale="zh_TW" value="中間庫連接設置" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.eas2wincos.client.Eas2wincosResource].resourceItems.resourceItem[JhdlaQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="Jhdla" />
            <lang locale="zh_HK" value="Jhdla" />
            <lang locale="zh_TW" value="Jhdla" />
        </rs>
    </resource>
</i18nResource>

