<?xml version="1.0" encoding="UTF-8"?>
<i18nResource xmlns="com.kingdee.bos.metadata">
    <package>com.kingdee.eas.custom.wages.food.client</package>
    <name>FoodResource</name>
    <alias>i18nResource[com.kingdee.eas.custom.wages.food.client.FoodResource].alias</alias>
    <description>i18nResource[com.kingdee.eas.custom.wages.food.client.FoodResource].description</description>
    <userDefined>true</userDefined>
    <className>com.kingdee.eas.custom.wages.food.client.FoodResource</className>
    <resourceItems>
        <resourceItem>
            <name>BasicPostFoodQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.wages.food.client.FoodResource].resourceItems.resourceItem[BasicPostFoodQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>WageFoodOrganQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.wages.food.client.FoodResource].resourceItems.resourceItem[WageFoodOrganQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>MonthFoodBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.wages.food.client.FoodResource].resourceItems.resourceItem[MonthFoodBillQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>TAttendanceRecordsQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.wages.food.client.FoodResource].resourceItems.resourceItem[TAttendanceRecordsQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>ProdasseindexQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.wages.food.client.FoodResource].resourceItems.resourceItem[ProdasseindexQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>AssessmentMeasureQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.wages.food.client.FoodResource].resourceItems.resourceItem[AssessmentMeasureQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CompAssessmentQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.wages.food.client.FoodResource].resourceItems.resourceItem[CompAssessmentQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>AchievementQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.wages.food.client.FoodResource].resourceItems.resourceItem[AchievementQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>AdjustFoodmoneyQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.wages.food.client.FoodResource].resourceItems.resourceItem[AdjustFoodmoneyQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
    </resourceItems>
    <resource>
        <rs key="i18nResource[com.kingdee.eas.custom.wages.food.client.FoodResource].alias">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.wages.food.client.FoodResource].description">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.wages.food.client.FoodResource].resourceItems.resourceItem[AchievementQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="绩效考核单" />
            <lang locale="zh_HK" value="績效考核單" />
            <lang locale="zh_TW" value="績效考核單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.wages.food.client.FoodResource].resourceItems.resourceItem[AdjustFoodmoneyQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="食品公司调整工资单" />
            <lang locale="zh_HK" value="食品公司調整工資單" />
            <lang locale="zh_TW" value="食品公司調整工資單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.wages.food.client.FoodResource].resourceItems.resourceItem[AssessmentMeasureQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="考核测算单" />
            <lang locale="zh_HK" value="考核測算單" />
            <lang locale="zh_TW" value="考核測算單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.wages.food.client.FoodResource].resourceItems.resourceItem[BasicPostFoodQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="后勤基础岗位" />
            <lang locale="zh_HK" value="後勤基礎崗位" />
            <lang locale="zh_TW" value="後勤基礎崗位" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.wages.food.client.FoodResource].resourceItems.resourceItem[CompAssessmentQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="综合考核指标" />
            <lang locale="zh_HK" value="綜合考核指標" />
            <lang locale="zh_TW" value="綜合考核指標" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.wages.food.client.FoodResource].resourceItems.resourceItem[MonthFoodBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="后勤月工资计算单" />
            <lang locale="zh_HK" value="後勤月工資計算單" />
            <lang locale="zh_TW" value="後勤月工資計算單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.wages.food.client.FoodResource].resourceItems.resourceItem[ProdasseindexQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="生产考核指标" />
            <lang locale="zh_HK" value="生產考核指標" />
            <lang locale="zh_TW" value="生產考核指標" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.wages.food.client.FoodResource].resourceItems.resourceItem[TAttendanceRecordsQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="后勤考勤记录表" />
            <lang locale="zh_HK" value="後勤考勤記錄表" />
            <lang locale="zh_TW" value="後勤考勤記錄表" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.wages.food.client.FoodResource].resourceItems.resourceItem[WageFoodOrganQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="后勤组织架构" />
            <lang locale="zh_HK" value="後勤組織架構" />
            <lang locale="zh_TW" value="後勤組織架構" />
        </rs>
    </resource>
</i18nResource>

