<?xml version="1.0" encoding="UTF-8"?>
<i18nResource xmlns="com.kingdee.bos.metadata">
    <package>com.kingdee.eas.custom.ccchargeback.client</package>
    <name>CcchargebackResource</name>
    <alias>i18nResource[com.kingdee.eas.custom.ccchargeback.client.CcchargebackResource].alias</alias>
    <description>i18nResource[com.kingdee.eas.custom.ccchargeback.client.CcchargebackResource].description</description>
    <userDefined>false</userDefined>
    <className>com.kingdee.eas.custom.ccchargeback.client.CcchargebackResource</className>
    <resourceItems>
        <resourceItem>
            <name>ChargeBackStdQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.ccchargeback.client.CcchargebackResource].resourceItems.resourceItem[ChargeBackStdQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CcChargeBackBizBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.ccchargeback.client.CcchargebackResource].resourceItems.resourceItem[CcChargeBackBizBillQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
    </resourceItems>
    <resource>
        <rs key="i18nResource[com.kingdee.eas.custom.ccchargeback.client.CcchargebackResource].alias">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.ccchargeback.client.CcchargebackResource].description">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.ccchargeback.client.CcchargebackResource].resourceItems.resourceItem[CcChargeBackBizBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="商品鸡扣款单" />
            <lang locale="zh_HK" value="商品雞扣款單" />
            <lang locale="zh_TW" value="商品雞扣款單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.ccchargeback.client.CcchargebackResource].resourceItems.resourceItem[ChargeBackStdQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="扣款标准" />
            <lang locale="zh_HK" value="扣款標準" />
            <lang locale="zh_TW" value="扣款標準" />
        </rs>
    </resource>
</i18nResource>

