<?xml version="1.0" encoding="UTF-8"?>
<i18nResource xmlns="com.kingdee.bos.metadata">
    <package>com.kingdee.eas.farm.farmer.client</package>
    <name>FarmerResource</name>
    <alias>i18nResource[com.kingdee.eas.farm.farmer.client.FarmerResource].alias</alias>
    <description>i18nResource[com.kingdee.eas.farm.farmer.client.FarmerResource].description</description>
    <userDefined>false</userDefined>
    <className>com.kingdee.eas.farm.farmer.client.FarmerResource</className>
    <resourceItems>
        <resourceItem>
            <name>FarmerResearchBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.farmer.client.FarmerResource].resourceItems.resourceItem[FarmerResearchBillQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
    </resourceItems>
    <resource>
        <rs key="i18nResource[com.kingdee.eas.farm.farmer.client.FarmerResource].alias">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.farmer.client.FarmerResource].description">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.farmer.client.FarmerResource].resourceItems.resourceItem[FarmerResearchBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="养殖户调查表" />
            <lang locale="zh_HK" value="養殖戶調查表" />
            <lang locale="zh_TW" value="養殖戶調查表" />
        </rs>
    </resource>
</i18nResource>

