<?xml version="1.0" encoding="UTF-8"?>
<i18nResource xmlns="com.kingdee.bos.metadata">
    <package>com.kingdee.eas.custom.bsxbudget.client</package>
    <name>BsxbudgetResource</name>
    <alias>i18nResource[com.kingdee.eas.custom.bsxbudget.client.BsxbudgetResource].alias</alias>
    <description>i18nResource[com.kingdee.eas.custom.bsxbudget.client.BsxbudgetResource].description</description>
    <userDefined>false</userDefined>
    <className>com.kingdee.eas.custom.bsxbudget.client.BsxbudgetResource</className>
    <resourceItems>
        <resourceItem>
            <name>BSXBudgetQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.bsxbudget.client.BsxbudgetResource].resourceItems.resourceItem[BSXBudgetQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>BSXBudgetFoodQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.bsxbudget.client.BsxbudgetResource].resourceItems.resourceItem[BSXBudgetFoodQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>BSXBudgetFeedQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.bsxbudget.client.BsxbudgetResource].resourceItems.resourceItem[BSXBudgetFeedQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>BSXBudgetGroupQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.bsxbudget.client.BsxbudgetResource].resourceItems.resourceItem[BSXBudgetGroupQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>BSXBugetGroupQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.bsxbudget.client.BsxbudgetResource].resourceItems.resourceItem[BSXBugetGroupQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>BSXBudgetOfFeedQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.bsxbudget.client.BsxbudgetResource].resourceItems.resourceItem[BSXBudgetOfFeedQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
    </resourceItems>
    <resource>
        <rs key="i18nResource[com.kingdee.eas.custom.bsxbudget.client.BsxbudgetResource].alias">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.bsxbudget.client.BsxbudgetResource].description">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.bsxbudget.client.BsxbudgetResource].resourceItems.resourceItem[BSXBudgetFeedQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="北三峡养殖场预算" />
            <lang locale="zh_HK" value="北三峽養殖場預算" />
            <lang locale="zh_TW" value="北三峽養殖場預算" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.bsxbudget.client.BsxbudgetResource].resourceItems.resourceItem[BSXBudgetFoodQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="食品厂预算" />
            <lang locale="zh_HK" value="食品廠預算" />
            <lang locale="zh_TW" value="食品廠預算" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.bsxbudget.client.BsxbudgetResource].resourceItems.resourceItem[BSXBudgetGroupQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="集团预算" />
            <lang locale="zh_HK" value="集團預算" />
            <lang locale="zh_TW" value="集團預算" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.bsxbudget.client.BsxbudgetResource].resourceItems.resourceItem[BSXBudgetOfFeedQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="养殖场预算" />
            <lang locale="zh_HK" value="養殖場預算" />
            <lang locale="zh_TW" value="養殖場預算" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.bsxbudget.client.BsxbudgetResource].resourceItems.resourceItem[BSXBudgetQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="北三峡预算" />
            <lang locale="zh_HK" value="北三峽預算" />
            <lang locale="zh_TW" value="北三峽預算" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.bsxbudget.client.BsxbudgetResource].resourceItems.resourceItem[BSXBugetGroupQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="北三峡集团预算" />
            <lang locale="zh_HK" value="北三峽集團預算" />
            <lang locale="zh_TW" value="北三峽集團預算" />
        </rs>
    </resource>
</i18nResource>

