<?xml version="1.0" encoding="UTF-8"?>
<i18nResource xmlns="com.kingdee.bos.metadata">
    <package>com.kingdee.eas.farm.breed.business.client</package>
    <name>BusinessResource</name>
    <alias>i18nResource[com.kingdee.eas.farm.breed.business.client.BusinessResource].alias</alias>
    <description>i18nResource[com.kingdee.eas.farm.breed.business.client.BusinessResource].description</description>
    <userDefined>true</userDefined>
    <className>com.kingdee.eas.farm.breed.business.client.BusinessResource</className>
    <resourceItems>
        <resourceItem>
            <name>CCLeaveBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.breed.business.client.BusinessResource].resourceItems.resourceItem[CCLeaveBillQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>FeedPlanQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.breed.business.client.BusinessResource].resourceItems.resourceItem[FeedPlanQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CCBreedPlanQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.breed.business.client.BusinessResource].resourceItems.resourceItem[CCBreedPlanQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CommecialChikenApplyFodderQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.breed.business.client.BusinessResource].resourceItems.resourceItem[CommecialChikenApplyFodderQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CarviousFeedPlanQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.breed.business.client.BusinessResource].resourceItems.resourceItem[CarviousFeedPlanQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>FeedWithHisNumberQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.breed.business.client.BusinessResource].resourceItems.resourceItem[FeedWithHisNumberQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
    </resourceItems>
    <resource>
        <rs key="i18nResource[com.kingdee.eas.farm.breed.business.client.BusinessResource].alias">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.breed.business.client.BusinessResource].description">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.breed.business.client.BusinessResource].resourceItems.resourceItem[CCBreedPlanQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="入栏计划" />
            <lang locale="zh_HK" value="入欄計畫" />
            <lang locale="zh_TW" value="入欄計畫" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.breed.business.client.BusinessResource].resourceItems.resourceItem[CCLeaveBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="商品鸡出场纪录" />
            <lang locale="zh_HK" value="商品雞出場紀錄" />
            <lang locale="zh_TW" value="商品雞出場紀錄" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.breed.business.client.BusinessResource].resourceItems.resourceItem[CarviousFeedPlanQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="商品代要料计划" />
            <lang locale="zh_HK" value="商品代要料計畫" />
            <lang locale="zh_TW" value="商品代要料計畫" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.breed.business.client.BusinessResource].resourceItems.resourceItem[CommecialChikenApplyFodderQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="商品鸡要料计划" />
            <lang locale="zh_HK" value="商品雞要料計畫" />
            <lang locale="zh_TW" value="商品雞要料計畫" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.breed.business.client.BusinessResource].resourceItems.resourceItem[FeedPlanQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="养殖计划" />
            <lang locale="zh_HK" value="養殖計畫" />
            <lang locale="zh_TW" value="養殖計畫" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.breed.business.client.BusinessResource].resourceItems.resourceItem[FeedWithHisNumberQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="饲料料号" />
            <lang locale="zh_HK" value="飼料料號" />
            <lang locale="zh_TW" value="飼料料號" />
        </rs>
    </resource>
</i18nResource>

