<?xml version="1.0" encoding="UTF-8"?>
<i18nResource xmlns="com.kingdee.bos.metadata">
    <package>com.kingdee.eas.custom.tocloud.client</package>
    <name>TocloudResource</name>
    <alias>i18nResource[com.kingdee.eas.custom.tocloud.client.TocloudResource].alias</alias>
    <description>i18nResource[com.kingdee.eas.custom.tocloud.client.TocloudResource].description</description>
    <userDefined>true</userDefined>
    <className>com.kingdee.eas.custom.tocloud.client.TocloudResource</className>
    <resourceItems>
        <resourceItem>
            <name>TargetSystemQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.tocloud.client.TocloudResource].resourceItems.resourceItem[TargetSystemQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>BizTypeQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.tocloud.client.TocloudResource].resourceItems.resourceItem[BizTypeQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>BaseDataRelQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.tocloud.client.TocloudResource].resourceItems.resourceItem[BaseDataRelQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>BaseDataTypeQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.tocloud.client.TocloudResource].resourceItems.resourceItem[BaseDataTypeQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>SynDateLogQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.tocloud.client.TocloudResource].resourceItems.resourceItem[SynDateLogQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>TestWzQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.tocloud.client.TocloudResource].resourceItems.resourceItem[TestWzQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
    </resourceItems>
    <resource>
        <rs key="i18nResource[com.kingdee.eas.custom.tocloud.client.TocloudResource].alias">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.tocloud.client.TocloudResource].description">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.tocloud.client.TocloudResource].resourceItems.resourceItem[BaseDataRelQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="基础资料映射" />
            <lang locale="zh_HK" value="基礎資料映射" />
            <lang locale="zh_TW" value="基礎資料映射" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.tocloud.client.TocloudResource].resourceItems.resourceItem[BaseDataTypeQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="基础资料类型" />
            <lang locale="zh_HK" value="基礎資料類型" />
            <lang locale="zh_TW" value="基礎資料類型" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.tocloud.client.TocloudResource].resourceItems.resourceItem[BizTypeQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="业务类型" />
            <lang locale="zh_HK" value="業務類型" />
            <lang locale="zh_TW" value="業務類型" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.tocloud.client.TocloudResource].resourceItems.resourceItem[SynDateLogQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="数据同步日志" />
            <lang locale="zh_HK" value="數據同步日誌" />
            <lang locale="zh_TW" value="數據同步日誌" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.tocloud.client.TocloudResource].resourceItems.resourceItem[TargetSystemQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="目标系统" />
            <lang locale="zh_HK" value="目標系統" />
            <lang locale="zh_TW" value="目標系統" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.tocloud.client.TocloudResource].resourceItems.resourceItem[TestWzQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="控件" />
            <lang locale="zh_HK" value="控件" />
            <lang locale="zh_TW" value="控件" />
        </rs>
    </resource>
</i18nResource>

