<?xml version="1.0" encoding="UTF-8"?>
<i18nResource xmlns="com.kingdee.bos.metadata">
    <package>com.kingdee.eas.custom.szcount.client</package>
    <name>SzcountResource</name>
    <alias>i18nResource[com.kingdee.eas.custom.szcount.client.SzcountResource].alias</alias>
    <description>i18nResource[com.kingdee.eas.custom.szcount.client.SzcountResource].description</description>
    <userDefined>true</userDefined>
    <className>com.kingdee.eas.custom.szcount.client.SzcountResource</className>
    <resourceItems>
        <resourceItem>
            <name>SzProdCountQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.szcount.client.SzcountResource].resourceItems.resourceItem[SzProdCountQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>SzSemiProductQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.szcount.client.SzcountResource].resourceItems.resourceItem[SzSemiProductQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>SzCountPositionSetQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.szcount.client.SzcountResource].resourceItems.resourceItem[SzCountPositionSetQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>MaterialConversionQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.szcount.client.SzcountResource].resourceItems.resourceItem[MaterialConversionQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CountPostProductsQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.szcount.client.SzcountResource].resourceItems.resourceItem[CountPostProductsQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>FreshDailyQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.szcount.client.SzcountResource].resourceItems.resourceItem[FreshDailyQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>ChickenBasicDataQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.szcount.client.SzcountResource].resourceItems.resourceItem[ChickenBasicDataQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>PackingConversionQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.szcount.client.SzcountResource].resourceItems.resourceItem[PackingConversionQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CountPosOtherQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.szcount.client.SzcountResource].resourceItems.resourceItem[CountPosOtherQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
    </resourceItems>
    <resource>
        <rs key="i18nResource[com.kingdee.eas.custom.szcount.client.SzcountResource].alias">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.szcount.client.SzcountResource].description">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.szcount.client.SzcountResource].resourceItems.resourceItem[ChickenBasicDataQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="鸡产品基本数据" />
            <lang locale="zh_HK" value="雞產品基本數據" />
            <lang locale="zh_TW" value="雞產品基本數據" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.szcount.client.SzcountResource].resourceItems.resourceItem[CountPosOtherQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="其他分类定义" />
            <lang locale="zh_HK" value="其他分類定義" />
            <lang locale="zh_TW" value="其他分類定義" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.szcount.client.SzcountResource].resourceItems.resourceItem[CountPostProductsQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="计数岗位对应产品" />
            <lang locale="zh_HK" value="計數崗位對應產品" />
            <lang locale="zh_TW" value="計數崗位對應產品" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.szcount.client.SzcountResource].resourceItems.resourceItem[FreshDailyQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="鲜品日报单" />
            <lang locale="zh_HK" value="鮮品日報單" />
            <lang locale="zh_TW" value="鮮品日報單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.szcount.client.SzcountResource].resourceItems.resourceItem[MaterialConversionQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="物料换算" />
            <lang locale="zh_HK" value="物料換算" />
            <lang locale="zh_TW" value="物料換算" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.szcount.client.SzcountResource].resourceItems.resourceItem[PackingConversionQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="包装换算关系" />
            <lang locale="zh_HK" value="包裝換算關係" />
            <lang locale="zh_TW" value="包裝換算關係" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.szcount.client.SzcountResource].resourceItems.resourceItem[SzCountPositionSetQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="双增计数岗位" />
            <lang locale="zh_HK" value="雙增計數崗位" />
            <lang locale="zh_TW" value="雙增計數崗位" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.szcount.client.SzcountResource].resourceItems.resourceItem[SzProdCountQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="双增成品计数" />
            <lang locale="zh_HK" value="雙增成品計數" />
            <lang locale="zh_TW" value="雙增成品計數" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.szcount.client.SzcountResource].resourceItems.resourceItem[SzSemiProductQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="双增半成品计数" />
            <lang locale="zh_HK" value="雙增半成品計數" />
            <lang locale="zh_TW" value="雙增半成品計數" />
        </rs>
    </resource>
</i18nResource>

