<?xml version="1.0" encoding="UTF-8"?>
<i18nResource xmlns="com.kingdee.bos.metadata">
    <package>com.kingdee.eas.delivery.basedata.client</package>
    <name>BasedataResource</name>
    <alias>i18nResource[com.kingdee.eas.delivery.basedata.client.BasedataResource].alias</alias>
    <description>i18nResource[com.kingdee.eas.delivery.basedata.client.BasedataResource].description</description>
    <userDefined>true</userDefined>
    <className>com.kingdee.eas.delivery.basedata.client.BasedataResource</className>
    <resourceItems>
        <resourceItem>
            <name>CarQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.delivery.basedata.client.BasedataResource].resourceItems.resourceItem[CarQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>DeliveryLineQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.delivery.basedata.client.BasedataResource].resourceItems.resourceItem[DeliveryLineQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
    </resourceItems>
    <resource>
        <rs key="i18nResource[com.kingdee.eas.delivery.basedata.client.BasedataResource].alias">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.delivery.basedata.client.BasedataResource].description">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.delivery.basedata.client.BasedataResource].resourceItems.resourceItem[CarQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="车辆" />
            <lang locale="zh_HK" value="車輛" />
            <lang locale="zh_TW" value="車輛" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.delivery.basedata.client.BasedataResource].resourceItems.resourceItem[DeliveryLineQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="发运路线" />
            <lang locale="zh_HK" value="發運路線" />
            <lang locale="zh_TW" value="發運路線" />
        </rs>
    </resource>
</i18nResource>

