<?xml version="1.0" encoding="UTF-8"?>
<i18nResource xmlns="com.kingdee.bos.metadata">
    <package>com.kingdee.eas.farm.breed.freedplan.client</package>
    <name>FreedplanResource</name>
    <alias>i18nResource[com.kingdee.eas.farm.breed.freedplan.client.FreedplanResource].alias</alias>
    <description>i18nResource[com.kingdee.eas.farm.breed.freedplan.client.FreedplanResource].description</description>
    <userDefined>true</userDefined>
    <className>com.kingdee.eas.farm.breed.freedplan.client.FreedplanResource</className>
    <resourceItems>
        <resourceItem>
            <name>BreedFodderPlanQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.breed.freedplan.client.FreedplanResource].resourceItems.resourceItem[BreedFodderPlanQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
    </resourceItems>
    <resource>
        <rs key="i18nResource[com.kingdee.eas.farm.breed.freedplan.client.FreedplanResource].alias">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.breed.freedplan.client.FreedplanResource].description">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.breed.freedplan.client.FreedplanResource].resourceItems.resourceItem[BreedFodderPlanQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="批次要料计划" />
            <lang locale="zh_HK" value="批次要料計畫" />
            <lang locale="zh_TW" value="批次要料計畫" />
        </rs>
    </resource>
</i18nResource>

