<?xml version="1.0" encoding="UTF-8"?>
<i18nResource xmlns="com.kingdee.bos.metadata">
    <package>com.kingdee.eas.custom.settlebill.client</package>
    <name>SettlebillResource</name>
    <alias>i18nResource[com.kingdee.eas.custom.settlebill.client.SettlebillResource].alias</alias>
    <description>i18nResource[com.kingdee.eas.custom.settlebill.client.SettlebillResource].description</description>
    <userDefined>false</userDefined>
    <className>com.kingdee.eas.custom.settlebill.client.SettlebillResource</className>
    <resourceItems>
        <resourceItem>
            <name>SettleBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.settlebill.client.SettlebillResource].resourceItems.resourceItem[SettleBillQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>RewardAndPunishProjectQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.settlebill.client.SettlebillResource].resourceItems.resourceItem[RewardAndPunishProjectQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>SettleItemQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.settlebill.client.SettlebillResource].resourceItems.resourceItem[SettleItemQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CarcassRateQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.settlebill.client.SettlebillResource].resourceItems.resourceItem[CarcassRateQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
    </resourceItems>
    <resource>
        <rs key="i18nResource[com.kingdee.eas.custom.settlebill.client.SettlebillResource].alias">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.settlebill.client.SettlebillResource].description">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.settlebill.client.SettlebillResource].resourceItems.resourceItem[CarcassRateQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="胴体出成折算标准" />
            <lang locale="zh_HK" value="胴體出成折算標準" />
            <lang locale="zh_TW" value="胴體出成折算標準" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.settlebill.client.SettlebillResource].resourceItems.resourceItem[RewardAndPunishProjectQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="奖惩项目" />
            <lang locale="zh_HK" value="獎懲項目" />
            <lang locale="zh_TW" value="獎懲項目" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.settlebill.client.SettlebillResource].resourceItems.resourceItem[SettleBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="结算单" />
            <lang locale="zh_HK" value="結算單" />
            <lang locale="zh_TW" value="結算單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.settlebill.client.SettlebillResource].resourceItems.resourceItem[SettleItemQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="结算项目" />
            <lang locale="zh_HK" value="結算項目" />
            <lang locale="zh_TW" value="結算項目" />
        </rs>
    </resource>
</i18nResource>

