<?xml version="1.0" encoding="UTF-8"?>
<i18nResource xmlns="com.kingdee.bos.metadata">
    <package>com.kingdee.eas.custom.eas2temp.client</package>
    <name>Eas2tempResource</name>
    <alias>i18nResource[com.kingdee.eas.custom.eas2temp.client.Eas2tempResource].alias</alias>
    <description>i18nResource[com.kingdee.eas.custom.eas2temp.client.Eas2tempResource].description</description>
    <userDefined>true</userDefined>
    <className>com.kingdee.eas.custom.eas2temp.client.Eas2tempResource</className>
    <resourceItems>
        <resourceItem>
            <name>DataBaseSettingQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.eas2temp.client.Eas2tempResource].resourceItems.resourceItem[DataBaseSettingQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>BillDeafultSettingQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.eas2temp.client.Eas2tempResource].resourceItems.resourceItem[BillDeafultSettingQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>TestQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.eas2temp.client.Eas2tempResource].resourceItems.resourceItem[TestQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Test1QueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.eas2temp.client.Eas2tempResource].resourceItems.resourceItem[Test1QueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>EASBarRelQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.eas2temp.client.Eas2tempResource].resourceItems.resourceItem[EASBarRelQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>BarMaterialRelQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.eas2temp.client.Eas2tempResource].resourceItems.resourceItem[BarMaterialRelQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
    </resourceItems>
    <resource>
        <rs key="i18nResource[com.kingdee.eas.custom.eas2temp.client.Eas2tempResource].alias">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.eas2temp.client.Eas2tempResource].description">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.eas2temp.client.Eas2tempResource].resourceItems.resourceItem[BarMaterialRelQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="BarMaterialRel" />
            <lang locale="zh_HK" value="BarMaterialRel" />
            <lang locale="zh_TW" value="BarMaterialRel" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.eas2temp.client.Eas2tempResource].resourceItems.resourceItem[BillDeafultSettingQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="导入中间库默认设置" />
            <lang locale="zh_HK" value="導入中間庫默認設置" />
            <lang locale="zh_TW" value="導入中間庫默認設置" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.eas2temp.client.Eas2tempResource].resourceItems.resourceItem[DataBaseSettingQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="中间库连接设置" />
            <lang locale="zh_HK" value="中間庫連接設置" />
            <lang locale="zh_TW" value="中間庫連接設置" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.eas2temp.client.Eas2tempResource].resourceItems.resourceItem[EASBarRelQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="条码物料对应关系" />
            <lang locale="zh_HK" value="條碼物料對應關係" />
            <lang locale="zh_TW" value="條碼物料對應關係" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.eas2temp.client.Eas2tempResource].resourceItems.resourceItem[Test1QueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="Test1" />
            <lang locale="zh_HK" value="Test1" />
            <lang locale="zh_TW" value="Test1" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.eas2temp.client.Eas2tempResource].resourceItems.resourceItem[TestQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="测试" />
            <lang locale="zh_HK" value="測試" />
            <lang locale="zh_TW" value="測試" />
        </rs>
    </resource>
</i18nResource>

