<?xml version="1.0" encoding="UTF-8"?>
<i18nResource xmlns="com.kingdee.bos.metadata">
    <package>com.kingdee.eas.custom.shr.client</package>
    <name>ShrResource</name>
    <alias>i18nResource[com.kingdee.eas.custom.shr.client.ShrResource].alias</alias>
    <description>i18nResource[com.kingdee.eas.custom.shr.client.ShrResource].description</description>
    <userDefined>false</userDefined>
    <className>com.kingdee.eas.custom.shr.client.ShrResource</className>
    <resourceItems>
        <resourceItem>
            <name>WincosForSHRQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.shr.client.ShrResource].resourceItems.resourceItem[WincosForSHRQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>PrePersonToPersonQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.shr.client.ShrResource].resourceItems.resourceItem[PrePersonToPersonQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
    </resourceItems>
    <resource>
        <rs key="i18nResource[com.kingdee.eas.custom.shr.client.ShrResource].alias">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.shr.client.ShrResource].description">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.shr.client.ShrResource].resourceItems.resourceItem[PrePersonToPersonQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="转入职单" />
            <lang locale="zh_HK" value="轉入職單" />
            <lang locale="zh_TW" value="轉入職單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.shr.client.ShrResource].resourceItems.resourceItem[WincosForSHRQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="SHR链接库设置" />
            <lang locale="zh_HK" value="SHR鏈接庫設置" />
            <lang locale="zh_TW" value="SHR鏈接庫設置" />
        </rs>
    </resource>
</i18nResource>

