<?xml version="1.0" encoding="UTF-8"?>
<i18nResource xmlns="com.kingdee.bos.metadata">
    <package>com.kingdee.eas.farm.breed.client</package>
    <name>BreedResource</name>
    <alias>i18nResource[com.kingdee.eas.farm.breed.client.BreedResource].alias</alias>
    <description>i18nResource[com.kingdee.eas.farm.breed.client.BreedResource].description</description>
    <userDefined>true</userDefined>
    <className>com.kingdee.eas.farm.breed.client.BreedResource</className>
    <resourceItems>
        <resourceItem>
            <name>HenhouseQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.breed.client.BreedResource].resourceItems.resourceItem[HenhouseQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>BreedModelQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.breed.client.BreedResource].resourceItems.resourceItem[BreedModelQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>BreedBatchQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.breed.client.BreedResource].resourceItems.resourceItem[BreedBatchQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>BreedStoorgSetQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.breed.client.BreedResource].resourceItems.resourceItem[BreedStoorgSetQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>BreedBatchEditBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.breed.client.BreedResource].resourceItems.resourceItem[BreedBatchEditBillQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CenterControlDeviceQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.breed.client.BreedResource].resourceItems.resourceItem[CenterControlDeviceQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>MaterialApplyBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.breed.client.BreedResource].resourceItems.resourceItem[MaterialApplyBillQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>ResidueSetQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.breed.client.BreedResource].resourceItems.resourceItem[ResidueSetQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>PlatFormPermissionQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.breed.client.BreedResource].resourceItems.resourceItem[PlatFormPermissionQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>FeedFettleQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.breed.client.BreedResource].resourceItems.resourceItem[FeedFettleQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>EntrustSettleStandardQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.breed.client.BreedResource].resourceItems.resourceItem[EntrustSettleStandardQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>BreedAreaQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.breed.client.BreedResource].resourceItems.resourceItem[BreedAreaQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>ParentBreedBatchQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.breed.client.BreedResource].resourceItems.resourceItem[ParentBreedBatchQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CompanyOwnBreedSetQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.breed.client.BreedResource].resourceItems.resourceItem[CompanyOwnBreedSetQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>HouseFieldQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.breed.client.BreedResource].resourceItems.resourceItem[HouseFieldQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>VarietieQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.breed.client.BreedResource].resourceItems.resourceItem[VarietieQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
    </resourceItems>
    <resource>
        <rs key="i18nResource[com.kingdee.eas.farm.breed.client.BreedResource].alias">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.breed.client.BreedResource].description">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.breed.client.BreedResource].resourceItems.resourceItem[BreedAreaQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="区" />
            <lang locale="zh_HK" value="區" />
            <lang locale="zh_TW" value="區" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.breed.client.BreedResource].resourceItems.resourceItem[BreedBatchEditBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="养殖批次编辑单" />
            <lang locale="zh_HK" value="養殖批次編輯單" />
            <lang locale="zh_TW" value="養殖批次編輯單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.breed.client.BreedResource].resourceItems.resourceItem[BreedBatchQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="养殖批次" />
            <lang locale="zh_HK" value="養殖批次" />
            <lang locale="zh_TW" value="養殖批次" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.breed.client.BreedResource].resourceItems.resourceItem[BreedModelQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="饲喂规范" />
            <lang locale="zh_HK" value="飼喂規範" />
            <lang locale="zh_TW" value="飼喂規範" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.breed.client.BreedResource].resourceItems.resourceItem[BreedStoorgSetQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="养殖场设置" />
            <lang locale="zh_HK" value="養殖場設置" />
            <lang locale="zh_TW" value="養殖場設置" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.breed.client.BreedResource].resourceItems.resourceItem[CenterControlDeviceQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="中控设备" />
            <lang locale="zh_HK" value="中控設備" />
            <lang locale="zh_TW" value="中控設備" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.breed.client.BreedResource].resourceItems.resourceItem[CompanyOwnBreedSetQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="自养基础设置" />
            <lang locale="zh_HK" value="自養基礎設置" />
            <lang locale="zh_TW" value="自養基礎設置" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.breed.client.BreedResource].resourceItems.resourceItem[EntrustSettleStandardQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="委托养殖结算标准" />
            <lang locale="zh_HK" value="委託養殖結算標準" />
            <lang locale="zh_TW" value="委託養殖結算標準" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.breed.client.BreedResource].resourceItems.resourceItem[FeedFettleQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="委托养殖结算单" />
            <lang locale="zh_HK" value="委託養殖結算單" />
            <lang locale="zh_TW" value="委託養殖結算單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.breed.client.BreedResource].resourceItems.resourceItem[HenhouseQueryF7WindowTitle].value">
            <lang locale="en_US" value="" />
            <lang locale="zh_CN" value="禽舍" />
            <lang locale="zh_HK" value="禽舍" />
            <lang locale="zh_TW" value="禽舍" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.breed.client.BreedResource].resourceItems.resourceItem[HouseFieldQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="栏位" />
            <lang locale="zh_HK" value="欄位" />
            <lang locale="zh_TW" value="欄位" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.breed.client.BreedResource].resourceItems.resourceItem[MaterialApplyBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="物料申请" />
            <lang locale="zh_HK" value="物料申請" />
            <lang locale="zh_TW" value="物料申請" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.breed.client.BreedResource].resourceItems.resourceItem[ParentBreedBatchQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="种禽养殖批次" />
            <lang locale="zh_HK" value="種禽養殖批次" />
            <lang locale="zh_TW" value="種禽養殖批次" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.breed.client.BreedResource].resourceItems.resourceItem[PlatFormPermissionQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="看板权限" />
            <lang locale="zh_HK" value="看板許可權" />
            <lang locale="zh_TW" value="看板許可權" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.breed.client.BreedResource].resourceItems.resourceItem[ResidueSetQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="残留时间设置" />
            <lang locale="zh_HK" value="殘留時間設置" />
            <lang locale="zh_TW" value="殘留時間設置" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.breed.client.BreedResource].resourceItems.resourceItem[VarietieQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="品种" />
            <lang locale="zh_HK" value="品種" />
            <lang locale="zh_TW" value="品種" />
        </rs>
    </resource>
</i18nResource>

