<?xml version="1.0" encoding="UTF-8"?>
<i18nResource xmlns="com.kingdee.bos.metadata">
    <package>com.kingdee.eas.farm.pig.ccpig.client</package>
    <name>CcpigResource</name>
    <alias>i18nResource[com.kingdee.eas.farm.pig.ccpig.client.CcpigResource].alias</alias>
    <description>i18nResource[com.kingdee.eas.farm.pig.ccpig.client.CcpigResource].description</description>
    <userDefined>true</userDefined>
    <className>com.kingdee.eas.farm.pig.ccpig.client.CcpigResource</className>
    <resourceItems>
        <resourceItem>
            <name>CCPigBatchQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.pig.ccpig.client.CcpigResource].resourceItems.resourceItem[CCPigBatchQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CCPigBreedModelQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.pig.ccpig.client.CcpigResource].resourceItems.resourceItem[CCPigBreedModelQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CCPigDailyQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.pig.ccpig.client.CcpigResource].resourceItems.resourceItem[CCPigDailyQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
    </resourceItems>
    <resource>
        <rs key="i18nResource[com.kingdee.eas.farm.pig.ccpig.client.CcpigResource].alias">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.pig.ccpig.client.CcpigResource].description">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.pig.ccpig.client.CcpigResource].resourceItems.resourceItem[CCPigBatchQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="商品猪批次" />
            <lang locale="zh_HK" value="商品豬批次" />
            <lang locale="zh_TW" value="商品豬批次" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.pig.ccpig.client.CcpigResource].resourceItems.resourceItem[CCPigBreedModelQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="商品猪养殖规范" />
            <lang locale="zh_HK" value="商品豬養殖規範" />
            <lang locale="zh_TW" value="商品豬養殖規範" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.pig.ccpig.client.CcpigResource].resourceItems.resourceItem[CCPigDailyQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="商品猪日报" />
            <lang locale="zh_HK" value="商品豬日報" />
            <lang locale="zh_TW" value="商品豬日報" />
        </rs>
    </resource>
</i18nResource>

