<?xml version="1.0" encoding="UTF-8"?>
<i18nResource xmlns="com.kingdee.bos.metadata">
    <package>com.kingdee.eas.farm.pig.breedingboar.client</package>
    <name>BreedingboarResource</name>
    <alias>i18nResource[com.kingdee.eas.farm.pig.breedingboar.client.BreedingboarResource].alias</alias>
    <description>i18nResource[com.kingdee.eas.farm.pig.breedingboar.client.BreedingboarResource].description</description>
    <userDefined>true</userDefined>
    <className>com.kingdee.eas.farm.pig.breedingboar.client.BreedingboarResource</className>
    <resourceItems>
        <resourceItem>
            <name>BreedingBoarBreedModelQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.pig.breedingboar.client.BreedingboarResource].resourceItems.resourceItem[BreedingBoarBreedModelQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>BoarQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.pig.breedingboar.client.BreedingboarResource].resourceItems.resourceItem[BoarQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>BoarInfoQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.pig.breedingboar.client.BreedingboarResource].resourceItems.resourceItem[BoarInfoQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CollectSpermBIllQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.pig.breedingboar.client.BreedingboarResource].resourceItems.resourceItem[CollectSpermBIllQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>SpermCheckBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.pig.breedingboar.client.BreedingboarResource].resourceItems.resourceItem[SpermCheckBillQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>BoarDailyQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.pig.breedingboar.client.BreedingboarResource].resourceItems.resourceItem[BoarDailyQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
    </resourceItems>
    <resource>
        <rs key="i18nResource[com.kingdee.eas.farm.pig.breedingboar.client.BreedingboarResource].alias">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.pig.breedingboar.client.BreedingboarResource].description">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.pig.breedingboar.client.BreedingboarResource].resourceItems.resourceItem[BoarDailyQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="种公猪养殖日报" />
            <lang locale="zh_HK" value="種公豬養殖日報" />
            <lang locale="zh_TW" value="種公豬養殖日報" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.pig.breedingboar.client.BreedingboarResource].resourceItems.resourceItem[BoarInfoQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="种公猪档案" />
            <lang locale="zh_HK" value="種公豬檔案" />
            <lang locale="zh_TW" value="種公豬檔案" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.pig.breedingboar.client.BreedingboarResource].resourceItems.resourceItem[BoarQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="种公猪档案" />
            <lang locale="zh_HK" value="種公豬檔案" />
            <lang locale="zh_TW" value="種公豬檔案" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.pig.breedingboar.client.BreedingboarResource].resourceItems.resourceItem[BreedingBoarBreedModelQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="种公猪养殖规范" />
            <lang locale="zh_HK" value="種公豬養殖規範" />
            <lang locale="zh_TW" value="種公豬養殖規範" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.pig.breedingboar.client.BreedingboarResource].resourceItems.resourceItem[CollectSpermBIllQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="采精记录单" />
            <lang locale="zh_HK" value="采精記錄單" />
            <lang locale="zh_TW" value="采精記錄單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.pig.breedingboar.client.BreedingboarResource].resourceItems.resourceItem[SpermCheckBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="精液检验记录单" />
            <lang locale="zh_HK" value="精液檢驗記錄單" />
            <lang locale="zh_TW" value="精液檢驗記錄單" />
        </rs>
    </resource>
</i18nResource>

