<?xml version="1.0" encoding="UTF-8"?>
<i18nResource xmlns="com.kingdee.bos.metadata">
    <package>com.kingdee.eas.farm.carnivorous.assistbiz.client</package>
    <name>AssistbizResource</name>
    <alias>i18nResource[com.kingdee.eas.farm.carnivorous.assistbiz.client.AssistbizResource].alias</alias>
    <description>i18nResource[com.kingdee.eas.farm.carnivorous.assistbiz.client.AssistbizResource].description</description>
    <userDefined>false</userDefined>
    <className>com.kingdee.eas.farm.carnivorous.assistbiz.client.AssistbizResource</className>
    <resourceItems>
        <resourceItem>
            <name>FreightBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.assistbiz.client.AssistbizResource].resourceItems.resourceItem[FreightBillQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>FreightMileageBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.assistbiz.client.AssistbizResource].resourceItems.resourceItem[FreightMileageBillQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CKGrowthFreightBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.assistbiz.client.AssistbizResource].resourceItems.resourceItem[CKGrowthFreightBillQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CyxKbSettingQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.assistbiz.client.AssistbizResource].resourceItems.resourceItem[CyxKbSettingQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CKFreigntBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.assistbiz.client.AssistbizResource].resourceItems.resourceItem[CKFreigntBillQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CKFreightBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.assistbiz.client.AssistbizResource].resourceItems.resourceItem[CKFreightBillQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>MonthFreightCalBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.assistbiz.client.AssistbizResource].resourceItems.resourceItem[MonthFreightCalBillQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
    </resourceItems>
    <resource>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.assistbiz.client.AssistbizResource].alias">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.assistbiz.client.AssistbizResource].description">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.assistbiz.client.AssistbizResource].resourceItems.resourceItem[CKFreightBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="毛鸡运费单" />
            <lang locale="zh_HK" value="毛雞運費單" />
            <lang locale="zh_TW" value="毛雞運費單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.assistbiz.client.AssistbizResource].resourceItems.resourceItem[CKFreigntBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="毛鸡运费单" />
            <lang locale="zh_HK" value="毛雞運費單" />
            <lang locale="zh_TW" value="毛雞運費單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.assistbiz.client.AssistbizResource].resourceItems.resourceItem[CKGrowthFreightBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="毛鸡增幅运费表" />
            <lang locale="zh_HK" value="毛雞增幅運費表" />
            <lang locale="zh_TW" value="毛雞增幅運費表" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.assistbiz.client.AssistbizResource].resourceItems.resourceItem[CyxKbSettingQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="翅淤血扣补" />
            <lang locale="zh_HK" value="翅淤血扣補" />
            <lang locale="zh_TW" value="翅淤血扣補" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.assistbiz.client.AssistbizResource].resourceItems.resourceItem[FreightBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="运费计算单" />
            <lang locale="zh_HK" value="運費計算單" />
            <lang locale="zh_TW" value="運費計算單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.assistbiz.client.AssistbizResource].resourceItems.resourceItem[FreightMileageBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="运费里程表" />
            <lang locale="zh_HK" value="運費裏程表" />
            <lang locale="zh_TW" value="運費裏程表" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.assistbiz.client.AssistbizResource].resourceItems.resourceItem[MonthFreightCalBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="月运费核算" />
            <lang locale="zh_HK" value="月運費核算" />
            <lang locale="zh_TW" value="月運費核算" />
        </rs>
    </resource>
</i18nResource>

