<?xml version="1.0" encoding="UTF-8"?>
<i18nResource xmlns="com.kingdee.bos.metadata">
    <package>com.kingdee.eas.custom.lhsm.client</package>
    <name>LhsmResource</name>
    <alias>i18nResource[com.kingdee.eas.custom.lhsm.client.LhsmResource].alias</alias>
    <description>i18nResource[com.kingdee.eas.custom.lhsm.client.LhsmResource].description</description>
    <userDefined>true</userDefined>
    <className>com.kingdee.eas.custom.lhsm.client.LhsmResource</className>
    <resourceItems>
        <resourceItem>
            <name>PurContractQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.lhsm.client.LhsmResource].resourceItems.resourceItem[PurContractQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>PurContractAQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.lhsm.client.LhsmResource].resourceItems.resourceItem[PurContractAQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>QualityQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.lhsm.client.LhsmResource].resourceItems.resourceItem[QualityQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>QualityItemQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.lhsm.client.LhsmResource].resourceItems.resourceItem[QualityItemQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>PurContractBQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.lhsm.client.LhsmResource].resourceItems.resourceItem[PurContractBQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>KPIDataQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.lhsm.client.LhsmResource].resourceItems.resourceItem[KPIDataQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>KpiQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.lhsm.client.LhsmResource].resourceItems.resourceItem[KpiQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>KpiDataAQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.lhsm.client.LhsmResource].resourceItems.resourceItem[KpiDataAQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>KpiDataCQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.lhsm.client.LhsmResource].resourceItems.resourceItem[KpiDataCQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>InWarehsDetailQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.lhsm.client.LhsmResource].resourceItems.resourceItem[InWarehsDetailQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>SaleForecastQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.lhsm.client.LhsmResource].resourceItems.resourceItem[SaleForecastQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CompanyInvQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.lhsm.client.LhsmResource].resourceItems.resourceItem[CompanyInvQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>SaleIssueBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.lhsm.client.LhsmResource].resourceItems.resourceItem[SaleIssueBillQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>MoveOutQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.lhsm.client.LhsmResource].resourceItems.resourceItem[MoveOutQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>MoveInQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.lhsm.client.LhsmResource].resourceItems.resourceItem[MoveInQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>DongtaiAAQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.lhsm.client.LhsmResource].resourceItems.resourceItem[DongtaiAAQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>FromStockReqSummaryQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.lhsm.client.LhsmResource].resourceItems.resourceItem[FromStockReqSummaryQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CompanyManageQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.lhsm.client.LhsmResource].resourceItems.resourceItem[CompanyManageQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>ContractAImproveQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.lhsm.client.LhsmResource].resourceItems.resourceItem[ContractAImproveQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>ReconcOtherBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.lhsm.client.LhsmResource].resourceItems.resourceItem[ReconcOtherBillQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>FiCompanyInterBQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.lhsm.client.LhsmResource].resourceItems.resourceItem[FiCompanyInterBQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>TrainSkinBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.lhsm.client.LhsmResource].resourceItems.resourceItem[TrainSkinBillQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>PersonGuaranteeQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.lhsm.client.LhsmResource].resourceItems.resourceItem[PersonGuaranteeQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>GuaranteeApplyQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.lhsm.client.LhsmResource].resourceItems.resourceItem[GuaranteeApplyQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
    </resourceItems>
    <resource>
        <rs key="i18nResource[com.kingdee.eas.custom.lhsm.client.LhsmResource].alias">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.lhsm.client.LhsmResource].description">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.lhsm.client.LhsmResource].resourceItems.resourceItem[CompanyInvQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="公司及时库存" />
            <lang locale="zh_HK" value="公司及時庫存" />
            <lang locale="zh_TW" value="公司及時庫存" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.lhsm.client.LhsmResource].resourceItems.resourceItem[CompanyManageQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="公司维护" />
            <lang locale="zh_HK" value="公司維護" />
            <lang locale="zh_TW" value="公司維護" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.lhsm.client.LhsmResource].resourceItems.resourceItem[ContractAImproveQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="合同调整单" />
            <lang locale="zh_HK" value="合同調整單" />
            <lang locale="zh_TW" value="合同調整單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.lhsm.client.LhsmResource].resourceItems.resourceItem[DongtaiAAQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="工程建设签呈" />
            <lang locale="zh_HK" value="工程建設簽呈" />
            <lang locale="zh_TW" value="工程建設簽呈" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.lhsm.client.LhsmResource].resourceItems.resourceItem[FiCompanyInterBQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="账户明细B" />
            <lang locale="zh_HK" value="賬戶明細B" />
            <lang locale="zh_TW" value="賬戶明細B" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.lhsm.client.LhsmResource].resourceItems.resourceItem[FromStockReqSummaryQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="要货汇总单" />
            <lang locale="zh_HK" value="要貨匯總單" />
            <lang locale="zh_TW" value="要貨匯總單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.lhsm.client.LhsmResource].resourceItems.resourceItem[GuaranteeApplyQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="担保申请单" />
            <lang locale="zh_HK" value="擔保申請單" />
            <lang locale="zh_TW" value="擔保申請單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.lhsm.client.LhsmResource].resourceItems.resourceItem[InWarehsDetailQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="发货明细单" />
            <lang locale="zh_HK" value="發貨明細單" />
            <lang locale="zh_TW" value="發貨明細單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.lhsm.client.LhsmResource].resourceItems.resourceItem[KPIDataQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="考核指标数据" />
            <lang locale="zh_HK" value="考核指標數據" />
            <lang locale="zh_TW" value="考核指標數據" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.lhsm.client.LhsmResource].resourceItems.resourceItem[KpiDataAQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="片区考核指标标准录入" />
            <lang locale="zh_HK" value="片區考核指標標準錄入" />
            <lang locale="zh_TW" value="片區考核指標標準錄入" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.lhsm.client.LhsmResource].resourceItems.resourceItem[KpiDataCQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="分公司考核指标数据录入" />
            <lang locale="zh_HK" value="分公司考核指標數據錄入" />
            <lang locale="zh_TW" value="分公司考核指標數據錄入" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.lhsm.client.LhsmResource].resourceItems.resourceItem[KpiQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="考核指标" />
            <lang locale="zh_HK" value="考核指標" />
            <lang locale="zh_TW" value="考核指標" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.lhsm.client.LhsmResource].resourceItems.resourceItem[MoveInQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="转入单" />
            <lang locale="zh_HK" value="轉入單" />
            <lang locale="zh_TW" value="轉入單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.lhsm.client.LhsmResource].resourceItems.resourceItem[MoveOutQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="MoveOut" />
            <lang locale="zh_HK" value="MoveOut" />
            <lang locale="zh_TW" value="MoveOut" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.lhsm.client.LhsmResource].resourceItems.resourceItem[PersonGuaranteeQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="担保人员资料" />
            <lang locale="zh_HK" value="擔保人員資料" />
            <lang locale="zh_TW" value="擔保人員資料" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.lhsm.client.LhsmResource].resourceItems.resourceItem[PurContractAQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="采购合同" />
            <lang locale="zh_HK" value="採購合同" />
            <lang locale="zh_TW" value="採購合同" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.lhsm.client.LhsmResource].resourceItems.resourceItem[PurContractBQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="片区采购合同" />
            <lang locale="zh_HK" value="片區採購合同" />
            <lang locale="zh_TW" value="片區採購合同" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.lhsm.client.LhsmResource].resourceItems.resourceItem[PurContractQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="采购合同" />
            <lang locale="zh_HK" value="採購合同" />
            <lang locale="zh_TW" value="採購合同" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.lhsm.client.LhsmResource].resourceItems.resourceItem[QualityItemQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="质量项" />
            <lang locale="zh_HK" value="質量項" />
            <lang locale="zh_TW" value="質量項" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.lhsm.client.LhsmResource].resourceItems.resourceItem[QualityQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="质量项目" />
            <lang locale="zh_HK" value="質量項目" />
            <lang locale="zh_TW" value="質量項目" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.lhsm.client.LhsmResource].resourceItems.resourceItem[ReconcOtherBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="付款对账单" />
            <lang locale="zh_HK" value="付款對賬單" />
            <lang locale="zh_TW" value="付款對賬單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.lhsm.client.LhsmResource].resourceItems.resourceItem[SaleForecastQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="销售预报单" />
            <lang locale="zh_HK" value="銷售預報單" />
            <lang locale="zh_TW" value="銷售預報單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.lhsm.client.LhsmResource].resourceItems.resourceItem[SaleIssueBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="销售出库单" />
            <lang locale="zh_HK" value="銷售出庫單" />
            <lang locale="zh_TW" value="銷售出庫單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.lhsm.client.LhsmResource].resourceItems.resourceItem[TrainSkinBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="火车皮信息维护" />
            <lang locale="zh_HK" value="火車皮信息維護" />
            <lang locale="zh_TW" value="火車皮信息維護" />
        </rs>
    </resource>
</i18nResource>

