<?xml version="1.0" encoding="UTF-8"?>
<i18nResource xmlns="com.kingdee.bos.metadata">
    <package>com.kingdee.eas.farm.foodtrac.client</package>
    <name>FoodtracResource</name>
    <alias>i18nResource[com.kingdee.eas.farm.foodtrac.client.FoodtracResource].alias</alias>
    <description>i18nResource[com.kingdee.eas.farm.foodtrac.client.FoodtracResource].description</description>
    <userDefined>true</userDefined>
    <className>com.kingdee.eas.farm.foodtrac.client.FoodtracResource</className>
    <resourceItems>
        <resourceItem>
            <name>FarmCodeQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.foodtrac.client.FoodtracResource].resourceItems.resourceItem[FarmCodeQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
    </resourceItems>
    <resource>
        <rs key="i18nResource[com.kingdee.eas.farm.foodtrac.client.FoodtracResource].alias">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.foodtrac.client.FoodtracResource].description">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.foodtrac.client.FoodtracResource].resourceItems.resourceItem[FarmCodeQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="养殖场编号" />
            <lang locale="zh_HK" value="養殖場編號" />
            <lang locale="zh_TW" value="養殖場編號" />
        </rs>
    </resource>
</i18nResource>

