<?xml version="1.0" encoding="UTF-8"?>
<i18nResource xmlns="com.kingdee.bos.metadata">
    <package>com.kingdee.eas.custom.mobileRPT.client</package>
    <name>MobileRPTResource</name>
    <alias>i18nResource[com.kingdee.eas.custom.mobileRPT.client.MobileRPTResource].alias</alias>
    <description>i18nResource[com.kingdee.eas.custom.mobileRPT.client.MobileRPTResource].description</description>
    <userDefined>true</userDefined>
    <className>com.kingdee.eas.custom.mobileRPT.client.MobileRPTResource</className>
    <resourceItems>
        <resourceItem>
            <name>RPTRoleQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.mobileRPT.client.MobileRPTResource].resourceItems.resourceItem[RPTRoleQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>TempQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.mobileRPT.client.MobileRPTResource].resourceItems.resourceItem[TempQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
    </resourceItems>
    <resource>
        <rs key="i18nResource[com.kingdee.eas.custom.mobileRPT.client.MobileRPTResource].alias">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.mobileRPT.client.MobileRPTResource].description">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.mobileRPT.client.MobileRPTResource].resourceItems.resourceItem[RPTRoleQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="报表权限" />
            <lang locale="zh_HK" value="報表許可權" />
            <lang locale="zh_TW" value="報表許可權" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.mobileRPT.client.MobileRPTResource].resourceItems.resourceItem[TempQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="Temp" />
            <lang locale="zh_HK" value="Temp" />
            <lang locale="zh_TW" value="Temp" />
        </rs>
    </resource>
</i18nResource>

