<?xml version="1.0" encoding="UTF-8"?>
<i18nResource xmlns="com.kingdee.bos.metadata">
    <package>com.kingdee.eas.farm.hatch.client</package>
    <name>HatchResource</name>
    <alias>i18nResource[com.kingdee.eas.farm.hatch.client.HatchResource].alias</alias>
    <description>i18nResource[com.kingdee.eas.farm.hatch.client.HatchResource].description</description>
    <userDefined>true</userDefined>
    <className>com.kingdee.eas.farm.hatch.client.HatchResource</className>
    <resourceItems>
        <resourceItem>
            <name>IncubatorQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.hatch.client.HatchResource].resourceItems.resourceItem[IncubatorQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>HatchingBoxQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.hatch.client.HatchResource].resourceItems.resourceItem[HatchingBoxQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>HatchBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.hatch.client.HatchResource].resourceItems.resourceItem[HatchBillQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>TranferBoxBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.hatch.client.HatchResource].resourceItems.resourceItem[TranferBoxBillQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>HatchBabyBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.hatch.client.HatchResource].resourceItems.resourceItem[HatchBabyBillQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>HatchBusinessDailyQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.hatch.client.HatchResource].resourceItems.resourceItem[HatchBusinessDailyQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>BatchPlanQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.hatch.client.HatchResource].resourceItems.resourceItem[BatchPlanQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>HatchBaseDataQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.hatch.client.HatchResource].resourceItems.resourceItem[HatchBaseDataQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>HatchEggReceivingBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.hatch.client.HatchResource].resourceItems.resourceItem[HatchEggReceivingBillQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>EggHatchBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.hatch.client.HatchResource].resourceItems.resourceItem[EggHatchBillQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>EggCandlingBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.hatch.client.HatchResource].resourceItems.resourceItem[EggCandlingBillQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>EggTrayingBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.hatch.client.HatchResource].resourceItems.resourceItem[EggTrayingBillQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>BEggHatchBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.hatch.client.HatchResource].resourceItems.resourceItem[BEggHatchBillQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>HatchAreaQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.hatch.client.HatchResource].resourceItems.resourceItem[HatchAreaQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>BEggCandlingBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.hatch.client.HatchResource].resourceItems.resourceItem[BEggCandlingBillQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>PipBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.hatch.client.HatchResource].resourceItems.resourceItem[PipBillQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>BEggTrayingBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.hatch.client.HatchResource].resourceItems.resourceItem[BEggTrayingBillQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>HatchHouseQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.hatch.client.HatchResource].resourceItems.resourceItem[HatchHouseQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>ImmuneBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.hatch.client.HatchResource].resourceItems.resourceItem[ImmuneBillQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>HatchAdjustBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.hatch.client.HatchResource].resourceItems.resourceItem[HatchAdjustBillQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>HatchBillCoefficientQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.hatch.client.HatchResource].resourceItems.resourceItem[HatchBillCoefficientQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CandlingBillInputModelQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.hatch.client.HatchResource].resourceItems.resourceItem[CandlingBillInputModelQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>EarlyEggStockQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.hatch.client.HatchResource].resourceItems.resourceItem[EarlyEggStockQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>SsQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.hatch.client.HatchResource].resourceItems.resourceItem[SsQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>ServiceItemsQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.hatch.client.HatchResource].resourceItems.resourceItem[ServiceItemsQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>HatchStandardQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.hatch.client.HatchResource].resourceItems.resourceItem[HatchStandardQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
    </resourceItems>
    <resource>
        <rs key="i18nResource[com.kingdee.eas.farm.hatch.client.HatchResource].alias">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.hatch.client.HatchResource].description">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.hatch.client.HatchResource].resourceItems.resourceItem[BEggCandlingBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="照蛋记录单" />
            <lang locale="zh_HK" value="照蛋記錄單" />
            <lang locale="zh_TW" value="照蛋記錄單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.hatch.client.HatchResource].resourceItems.resourceItem[BEggHatchBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="种蛋上孵单" />
            <lang locale="zh_HK" value="種蛋上孵單" />
            <lang locale="zh_TW" value="種蛋上孵單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.hatch.client.HatchResource].resourceItems.resourceItem[BEggTrayingBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="落盘记录单" />
            <lang locale="zh_HK" value="落盤記錄單" />
            <lang locale="zh_TW" value="落盤記錄單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.hatch.client.HatchResource].resourceItems.resourceItem[BatchPlanQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="上孵计划" />
            <lang locale="zh_HK" value="上孵計畫" />
            <lang locale="zh_TW" value="上孵計畫" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.hatch.client.HatchResource].resourceItems.resourceItem[CandlingBillInputModelQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="照蛋输入模式" />
            <lang locale="zh_HK" value="照蛋輸入模式" />
            <lang locale="zh_TW" value="照蛋輸入模式" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.hatch.client.HatchResource].resourceItems.resourceItem[EarlyEggStockQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="种禽养殖户种蛋库存期初" />
            <lang locale="zh_HK" value="種禽養殖戶種蛋庫存期初" />
            <lang locale="zh_TW" value="種禽養殖戶種蛋庫存期初" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.hatch.client.HatchResource].resourceItems.resourceItem[EggCandlingBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="照蛋记录单" />
            <lang locale="zh_HK" value="照蛋記錄單" />
            <lang locale="zh_TW" value="照蛋記錄單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.hatch.client.HatchResource].resourceItems.resourceItem[EggHatchBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="种蛋上孵单" />
            <lang locale="zh_HK" value="種蛋上孵單" />
            <lang locale="zh_TW" value="種蛋上孵單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.hatch.client.HatchResource].resourceItems.resourceItem[EggTrayingBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="落盘记录单" />
            <lang locale="zh_HK" value="落盤記錄單" />
            <lang locale="zh_TW" value="落盤記錄單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.hatch.client.HatchResource].resourceItems.resourceItem[HatchAdjustBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="孵化调整单" />
            <lang locale="zh_HK" value="孵化調整單" />
            <lang locale="zh_TW" value="孵化調整單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.hatch.client.HatchResource].resourceItems.resourceItem[HatchAreaQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="入孵区域" />
            <lang locale="zh_HK" value="入孵區域" />
            <lang locale="zh_TW" value="入孵區域" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.hatch.client.HatchResource].resourceItems.resourceItem[HatchBabyBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="出雏单" />
            <lang locale="zh_HK" value="出雛單" />
            <lang locale="zh_TW" value="出雛單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.hatch.client.HatchResource].resourceItems.resourceItem[HatchBaseDataQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="孵化基础资料" />
            <lang locale="zh_HK" value="孵化基礎資料" />
            <lang locale="zh_TW" value="孵化基礎資料" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.hatch.client.HatchResource].resourceItems.resourceItem[HatchBillCoefficientQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="层盘枚系数设置" />
            <lang locale="zh_HK" value="層盤枚係數設置" />
            <lang locale="zh_TW" value="層盤枚係數設置" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.hatch.client.HatchResource].resourceItems.resourceItem[HatchBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="上孵单" />
            <lang locale="zh_HK" value="上孵單" />
            <lang locale="zh_TW" value="上孵單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.hatch.client.HatchResource].resourceItems.resourceItem[HatchBusinessDailyQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="孵化经营日报" />
            <lang locale="zh_HK" value="孵化經營日報" />
            <lang locale="zh_TW" value="孵化經營日報" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.hatch.client.HatchResource].resourceItems.resourceItem[HatchEggReceivingBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="种蛋接收单" />
            <lang locale="zh_HK" value="種蛋接收單" />
            <lang locale="zh_TW" value="種蛋接收單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.hatch.client.HatchResource].resourceItems.resourceItem[HatchHouseQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="上孵厅" />
            <lang locale="zh_HK" value="上孵廳" />
            <lang locale="zh_TW" value="上孵廳" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.hatch.client.HatchResource].resourceItems.resourceItem[HatchStandardQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="孵化规范" />
            <lang locale="zh_HK" value="孵化規範" />
            <lang locale="zh_TW" value="孵化規範" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.hatch.client.HatchResource].resourceItems.resourceItem[HatchingBoxQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="出雏箱" />
            <lang locale="zh_HK" value="出雛箱" />
            <lang locale="zh_TW" value="出雛箱" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.hatch.client.HatchResource].resourceItems.resourceItem[ImmuneBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="免疫派工单" />
            <lang locale="zh_HK" value="免疫派工單" />
            <lang locale="zh_TW" value="免疫派工單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.hatch.client.HatchResource].resourceItems.resourceItem[IncubatorQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="孵化箱" />
            <lang locale="zh_HK" value="孵化箱" />
            <lang locale="zh_TW" value="孵化箱" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.hatch.client.HatchResource].resourceItems.resourceItem[PipBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="落盘记录单" />
            <lang locale="zh_HK" value="落盤記錄單" />
            <lang locale="zh_TW" value="落盤記錄單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.hatch.client.HatchResource].resourceItems.resourceItem[ServiceItemsQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="服务项目" />
            <lang locale="zh_HK" value="服務項目" />
            <lang locale="zh_TW" value="服務項目" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.hatch.client.HatchResource].resourceItems.resourceItem[SsQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="Ss" />
            <lang locale="zh_HK" value="Ss" />
            <lang locale="zh_TW" value="Ss" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.hatch.client.HatchResource].resourceItems.resourceItem[TranferBoxBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="转箱单" />
            <lang locale="zh_HK" value="轉箱單" />
            <lang locale="zh_TW" value="轉箱單" />
        </rs>
    </resource>
</i18nResource>

