<?xml version="1.0" encoding="UTF-8"?>
<i18nResource xmlns="com.kingdee.bos.metadata">
    <package>com.kingdee.eas.custom.taihe.workshopmanager.client</package>
    <name>WorkshopmanagerResource</name>
    <alias>i18nResource[com.kingdee.eas.custom.taihe.workshopmanager.client.WorkshopmanagerResource].alias</alias>
    <description>i18nResource[com.kingdee.eas.custom.taihe.workshopmanager.client.WorkshopmanagerResource].description</description>
    <userDefined>false</userDefined>
    <className>com.kingdee.eas.custom.taihe.workshopmanager.client.WorkshopmanagerResource</className>
    <resourceItems>
        <resourceItem>
            <name>LoadingBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.taihe.workshopmanager.client.WorkshopmanagerResource].resourceItems.resourceItem[LoadingBillQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>WorkshopDeafultSettingQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.taihe.workshopmanager.client.WorkshopmanagerResource].resourceItems.resourceItem[WorkshopDeafultSettingQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
    </resourceItems>
    <resource>
        <rs key="i18nResource[com.kingdee.eas.custom.taihe.workshopmanager.client.WorkshopmanagerResource].alias">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.taihe.workshopmanager.client.WorkshopmanagerResource].description">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.taihe.workshopmanager.client.WorkshopmanagerResource].resourceItems.resourceItem[LoadingBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="装货单" />
            <lang locale="zh_HK" value="裝貨單" />
            <lang locale="zh_TW" value="裝貨單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.taihe.workshopmanager.client.WorkshopmanagerResource].resourceItems.resourceItem[WorkshopDeafultSettingQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="车间管理基础设置" />
            <lang locale="zh_HK" value="車間管理基礎設置" />
            <lang locale="zh_TW" value="車間管理基礎設置" />
        </rs>
    </resource>
</i18nResource>

