<?xml version="1.0" encoding="UTF-8"?>
<i18nResource xmlns="com.kingdee.bos.metadata">
    <package>com.kingdee.eas.custom.taihe.vehicledetection.client</package>
    <name>VehicledetectionResource</name>
    <alias>i18nResource[com.kingdee.eas.custom.taihe.vehicledetection.client.VehicledetectionResource].alias</alias>
    <description>i18nResource[com.kingdee.eas.custom.taihe.vehicledetection.client.VehicledetectionResource].description</description>
    <userDefined>false</userDefined>
    <className>com.kingdee.eas.custom.taihe.vehicledetection.client.VehicledetectionResource</className>
    <resourceItems>
        <resourceItem>
            <name>VdChannelSettingQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.taihe.vehicledetection.client.VehicledetectionResource].resourceItems.resourceItem[VdChannelSettingQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>VcWhiteListQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.taihe.vehicledetection.client.VehicledetectionResource].resourceItems.resourceItem[VcWhiteListQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
    </resourceItems>
    <resource>
        <rs key="i18nResource[com.kingdee.eas.custom.taihe.vehicledetection.client.VehicledetectionResource].alias">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.taihe.vehicledetection.client.VehicledetectionResource].description">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.taihe.vehicledetection.client.VehicledetectionResource].resourceItems.resourceItem[VcWhiteListQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="白名单" />
            <lang locale="zh_HK" value="白名單" />
            <lang locale="zh_TW" value="白名單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.taihe.vehicledetection.client.VehicledetectionResource].resourceItems.resourceItem[VdChannelSettingQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="通道设置" />
            <lang locale="zh_HK" value="通道設置" />
            <lang locale="zh_TW" value="通道設置" />
        </rs>
    </resource>
</i18nResource>

