<?xml version="1.0" encoding="UTF-8"?>
<i18nResource xmlns="com.kingdee.bos.metadata">
    <package>com.kingdee.eas.custom.taihe.basesetting.client</package>
    <name>BasesettingResource</name>
    <alias>i18nResource[com.kingdee.eas.custom.taihe.basesetting.client.BasesettingResource].alias</alias>
    <description>i18nResource[com.kingdee.eas.custom.taihe.basesetting.client.BasesettingResource].description</description>
    <userDefined>false</userDefined>
    <className>com.kingdee.eas.custom.taihe.basesetting.client.BasesettingResource</className>
    <resourceItems>
        <resourceItem>
            <name>TaiheBaseSettingQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.taihe.basesetting.client.BasesettingResource].resourceItems.resourceItem[TaiheBaseSettingQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
    </resourceItems>
    <resource>
        <rs key="i18nResource[com.kingdee.eas.custom.taihe.basesetting.client.BasesettingResource].alias">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.taihe.basesetting.client.BasesettingResource].description">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.taihe.basesetting.client.BasesettingResource].resourceItems.resourceItem[TaiheBaseSettingQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="基础设置" />
            <lang locale="zh_TW" value="null" />
        </rs>
    </resource>
</i18nResource>

