<?xml version="1.0" encoding="UTF-8"?>
<i18nResource xmlns="com.kingdee.bos.metadata">
    <package>com.kingdee.eas.custom.znck.client</package>
    <name>ZnckResource</name>
    <alias>i18nResource[com.kingdee.eas.custom.znck.client.ZnckResource].alias</alias>
    <description>i18nResource[com.kingdee.eas.custom.znck.client.ZnckResource].description</description>
    <userDefined>true</userDefined>
    <className>com.kingdee.eas.custom.znck.client.ZnckResource</className>
    <resourceItems>
        <resourceItem>
            <name>MaterialLedRelQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.znck.client.ZnckResource].resourceItems.resourceItem[MaterialLedRelQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
    </resourceItems>
    <resource>
        <rs key="i18nResource[com.kingdee.eas.custom.znck.client.ZnckResource].alias">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.znck.client.ZnckResource].description">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.znck.client.ZnckResource].resourceItems.resourceItem[MaterialLedRelQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="配件与库位灯关联表" />
            <lang locale="zh_HK" value="配件與庫位燈關聯表" />
            <lang locale="zh_TW" value="配件與庫位燈關聯表" />
        </rs>
    </resource>
</i18nResource>

