<?xml version="1.0" encoding="UTF-8"?>
<i18nResource xmlns="com.kingdee.bos.metadata">
    <package>com.kingdee.eas.custom.salaryvoucher.client</package>
    <name>SalaryvoucherResource</name>
    <alias>i18nResource[com.kingdee.eas.custom.salaryvoucher.client.SalaryvoucherResource].alias</alias>
    <description>i18nResource[com.kingdee.eas.custom.salaryvoucher.client.SalaryvoucherResource].description</description>
    <userDefined>false</userDefined>
    <className>com.kingdee.eas.custom.salaryvoucher.client.SalaryvoucherResource</className>
    <resourceItems>
        <resourceItem>
            <name>SalaryVoucherQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.salaryvoucher.client.SalaryvoucherResource].resourceItems.resourceItem[SalaryVoucherQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Test000QueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.salaryvoucher.client.SalaryvoucherResource].resourceItems.resourceItem[Test000QueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>SCalSchemeQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.salaryvoucher.client.SalaryvoucherResource].resourceItems.resourceItem[SCalSchemeQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>ConnectServerQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.salaryvoucher.client.SalaryvoucherResource].resourceItems.resourceItem[ConnectServerQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
    </resourceItems>
    <resource>
        <rs key="i18nResource[com.kingdee.eas.custom.salaryvoucher.client.SalaryvoucherResource].alias">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.salaryvoucher.client.SalaryvoucherResource].description">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.salaryvoucher.client.SalaryvoucherResource].resourceItems.resourceItem[ConnectServerQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="外部服务器连接" />
            <lang locale="zh_HK" value="外部服務器連接" />
            <lang locale="zh_TW" value="外部服務器連接" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.salaryvoucher.client.SalaryvoucherResource].resourceItems.resourceItem[SCalSchemeQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="薪酬方案" />
            <lang locale="zh_HK" value="薪酬方案" />
            <lang locale="zh_TW" value="薪酬方案" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.salaryvoucher.client.SalaryvoucherResource].resourceItems.resourceItem[SalaryVoucherQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="薪酬凭证" />
            <lang locale="zh_HK" value="薪酬憑證" />
            <lang locale="zh_TW" value="薪酬憑證" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.salaryvoucher.client.SalaryvoucherResource].resourceItems.resourceItem[Test000QueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="Test000" />
            <lang locale="zh_HK" value="Test000" />
            <lang locale="zh_TW" value="Test000" />
        </rs>
    </resource>
</i18nResource>

