<?xml version="1.0" encoding="UTF-8"?>
<i18nResource xmlns="com.kingdee.bos.metadata">
    <package>com.kingdee.eas.farm.food.client</package>
    <name>FoodResource</name>
    <alias>i18nResource[com.kingdee.eas.farm.food.client.FoodResource].alias</alias>
    <description>i18nResource[com.kingdee.eas.farm.food.client.FoodResource].description</description>
    <userDefined>true</userDefined>
    <className>com.kingdee.eas.farm.food.client.FoodResource</className>
    <resourceItems>
        <resourceItem>
            <name>CCReceivingBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.food.client.FoodResource].resourceItems.resourceItem[CCReceivingBillQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>FreshCountBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.food.client.FoodResource].resourceItems.resourceItem[FreshCountBillQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CoutBillSettingQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.food.client.FoodResource].resourceItems.resourceItem[CoutBillSettingQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>ChickenDailyQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.food.client.FoodResource].resourceItems.resourceItem[ChickenDailyQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>FuleDaliyQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.food.client.FoodResource].resourceItems.resourceItem[FuleDaliyQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>TransportDailyQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.food.client.FoodResource].resourceItems.resourceItem[TransportDailyQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>PersonDailQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.food.client.FoodResource].resourceItems.resourceItem[PersonDailQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>PersonDailyQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.food.client.FoodResource].resourceItems.resourceItem[PersonDailyQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CManufactureBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.food.client.FoodResource].resourceItems.resourceItem[CManufactureBillQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>FoodBaseDataQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.food.client.FoodResource].resourceItems.resourceItem[FoodBaseDataQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>FoodSendCarPlanQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.food.client.FoodResource].resourceItems.resourceItem[FoodSendCarPlanQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CarExcuteCircsQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.food.client.FoodResource].resourceItems.resourceItem[CarExcuteCircsQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>DeliveryCarQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.food.client.FoodResource].resourceItems.resourceItem[DeliveryCarQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
         <resourceItem>
            <name>OutsidePersonRecordBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.food.client.FoodResource].resourceItems.resourceItem[OutsidePersonRecordBillQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>SlaughterPlanQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.food.client.FoodResource].resourceItems.resourceItem[SlaughterPlanQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
    </resourceItems>
    <resource>
        <rs key="i18nResource[com.kingdee.eas.farm.food.client.FoodResource].alias">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.food.client.FoodResource].description">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.food.client.FoodResource].resourceItems.resourceItem[CCReceivingBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="" />
            <lang locale="zh_CN" value="商品鸡接收单" />
            <lang locale="zh_HK" value="商品雞接收單" />
            <lang locale="zh_TW" value="商品雞接收單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.food.client.FoodResource].resourceItems.resourceItem[CManufactureBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="生产入库单" />
            <lang locale="zh_HK" value="生產入庫單" />
            <lang locale="zh_TW" value="生產入庫單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.food.client.FoodResource].resourceItems.resourceItem[CarExcuteCircsQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="派车执行情况表" />
            <lang locale="zh_HK" value="派車執行情況表" />
            <lang locale="zh_TW" value="派車執行情況表" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.food.client.FoodResource].resourceItems.resourceItem[ChickenDailyQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="商品鸡统计" />
            <lang locale="zh_HK" value="商品雞統計" />
            <lang locale="zh_TW" value="商品雞統計" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.food.client.FoodResource].resourceItems.resourceItem[CoutBillSettingQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="计数单基础设置" />
            <lang locale="zh_HK" value="計數單基礎設置" />
            <lang locale="zh_TW" value="計數單基礎設置" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.food.client.FoodResource].resourceItems.resourceItem[DeliveryCarQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="送货车辆" />
            <lang locale="zh_HK" value="送貨車輛" />
            <lang locale="zh_TW" value="送貨車輛" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.food.client.FoodResource].resourceItems.resourceItem[FoodBaseDataQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="食品厂基础设置" />
            <lang locale="zh_HK" value="食品廠基礎設置" />
            <lang locale="zh_TW" value="食品廠基礎設置" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.food.client.FoodResource].resourceItems.resourceItem[FoodSendCarPlanQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="食品厂派车计划" />
            <lang locale="zh_HK" value="食品廠派車計畫" />
            <lang locale="zh_TW" value="食品廠派車計畫" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.food.client.FoodResource].resourceItems.resourceItem[FreshCountBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="鲜品计数单" />
            <lang locale="zh_HK" value="鮮品計數單" />
            <lang locale="zh_TW" value="鮮品計數單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.food.client.FoodResource].resourceItems.resourceItem[FuleDaliyQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="燃料消耗统计" />
            <lang locale="zh_HK" value="燃料消耗統計" />
            <lang locale="zh_TW" value="燃料消耗統計" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.food.client.FoodResource].resourceItems.resourceItem[OutsidePersonRecordBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="OutsidePersonRecordBill" />
            <lang locale="zh_HK" value="OutsidePersonRecordBill" />
            <lang locale="zh_TW" value="OutsidePersonRecordBill" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.food.client.FoodResource].resourceItems.resourceItem[PersonDailQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="员工统计" />
            <lang locale="zh_HK" value="員工統計" />
            <lang locale="zh_TW" value="員工統計" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.food.client.FoodResource].resourceItems.resourceItem[PersonDailyQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="员工出勤统计" />
            <lang locale="zh_HK" value="員工出勤統計" />
            <lang locale="zh_TW" value="員工出勤統計" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.food.client.FoodResource].resourceItems.resourceItem[SlaughterPlanQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="屠宰计划" />
            <lang locale="zh_HK" value="屠宰計畫" />
            <lang locale="zh_TW" value="屠宰計畫" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.food.client.FoodResource].resourceItems.resourceItem[TransportDailyQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="车辆运输统计" />
            <lang locale="zh_HK" value="車輛運輸統計" />
            <lang locale="zh_TW" value="車輛運輸統計" />
        </rs>
    </resource>
</i18nResource>

