<?xml version="1.0" encoding="UTF-8"?>
<i18nResource xmlns="com.kingdee.bos.metadata">
    <package>com.kingdee.eas.message.client</package>
    <name>MessageResource</name>
    <alias>i18nResource[com.kingdee.eas.message.client.MessageResource].alias</alias>
    <description>i18nResource[com.kingdee.eas.message.client.MessageResource].description</description>
    <userDefined>true</userDefined>
    <className>com.kingdee.eas.message.client.MessageResource</className>
    <resourceItems>
        <resourceItem>
            <name>BaseSettingQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.message.client.MessageResource].resourceItems.resourceItem[BaseSettingQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
    </resourceItems>
    <resource>
        <rs key="i18nResource[com.kingdee.eas.message.client.MessageResource].alias">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.message.client.MessageResource].description">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.message.client.MessageResource].resourceItems.resourceItem[BaseSettingQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="基础设置" />
            <lang locale="zh_HK" value="基礎設置" />
            <lang locale="zh_TW" value="基礎設置" />
        </rs>
    </resource>
</i18nResource>

