<?xml version="1.0" encoding="UTF-8"?>
<i18nResource xmlns="com.kingdee.bos.metadata">
    <package>com.kingdee.eas.farm.feedfactory.client</package>
    <name>FeedfactoryResource</name>
    <alias>i18nResource[com.kingdee.eas.farm.feedfactory.client.FeedfactoryResource].alias</alias>
    <description>i18nResource[com.kingdee.eas.farm.feedfactory.client.FeedfactoryResource].description</description>
    <userDefined>true</userDefined>
    <className>com.kingdee.eas.farm.feedfactory.client.FeedfactoryResource</className>
    <resourceItems>
        <resourceItem>
            <name>QualityCheckBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.feedfactory.client.FeedfactoryResource].resourceItems.resourceItem[QualityCheckBillQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>FeedBusinessDailyQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.feedfactory.client.FeedfactoryResource].resourceItems.resourceItem[FeedBusinessDailyQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>PurFrightQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.feedfactory.client.FeedfactoryResource].resourceItems.resourceItem[PurFrightQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>LocalPurMATPriceQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.feedfactory.client.FeedfactoryResource].resourceItems.resourceItem[LocalPurMATPriceQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
    </resourceItems>
    <resource>
        <rs key="i18nResource[com.kingdee.eas.farm.feedfactory.client.FeedfactoryResource].alias">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.feedfactory.client.FeedfactoryResource].description">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.feedfactory.client.FeedfactoryResource].resourceItems.resourceItem[FeedBusinessDailyQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="饲料经营日报" />
            <lang locale="zh_HK" value="飼料經營日報" />
            <lang locale="zh_TW" value="飼料經營日報" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.feedfactory.client.FeedfactoryResource].resourceItems.resourceItem[LocalPurMATPriceQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="本地收购物料价格维护" />
            <lang locale="zh_HK" value="本地收購物料價格維護" />
            <lang locale="zh_TW" value="本地收購物料價格維護" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.feedfactory.client.FeedfactoryResource].resourceItems.resourceItem[PurFrightQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="采购运费单" />
            <lang locale="zh_HK" value="採購運費單" />
            <lang locale="zh_TW" value="採購運費單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.feedfactory.client.FeedfactoryResource].resourceItems.resourceItem[QualityCheckBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="质检单" />
            <lang locale="zh_HK" value="質檢單" />
            <lang locale="zh_TW" value="質檢單" />
        </rs>
    </resource>
</i18nResource>

