<?xml version="1.0" encoding="UTF-8"?>
<i18nResource xmlns="com.kingdee.bos.metadata">
    <package>com.kingdee.eas.custom.foodtrac.client</package>
    <name>FoodtracResource</name>
    <alias>i18nResource[com.kingdee.eas.custom.foodtrac.client.FoodtracResource].alias</alias>
    <description>i18nResource[com.kingdee.eas.custom.foodtrac.client.FoodtracResource].description</description>
    <userDefined>false</userDefined>
    <className>com.kingdee.eas.custom.foodtrac.client.FoodtracResource</className>
    <resourceItems>
        <resourceItem>
            <name>CompanyInfoQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.foodtrac.client.FoodtracResource].resourceItems.resourceItem[CompanyInfoQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>ProductCategoryInfoQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.foodtrac.client.FoodtracResource].resourceItems.resourceItem[ProductCategoryInfoQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>ProcesstechQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.foodtrac.client.FoodtracResource].resourceItems.resourceItem[ProcesstechQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>RawmaterialinfoQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.foodtrac.client.FoodtracResource].resourceItems.resourceItem[RawmaterialinfoQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CountrycheckQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.foodtrac.client.FoodtracResource].resourceItems.resourceItem[CountrycheckQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>ThirdpartycheckQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.foodtrac.client.FoodtracResource].resourceItems.resourceItem[ThirdpartycheckQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>LeavecheckQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.foodtrac.client.FoodtracResource].resourceItems.resourceItem[LeavecheckQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
    </resourceItems>
    <resource>
        <rs key="i18nResource[com.kingdee.eas.custom.foodtrac.client.FoodtracResource].alias">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.foodtrac.client.FoodtracResource].description">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.foodtrac.client.FoodtracResource].resourceItems.resourceItem[CompanyInfoQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="公司信息" />
            <lang locale="zh_HK" value="公司信息" />
            <lang locale="zh_TW" value="公司信息" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.foodtrac.client.FoodtracResource].resourceItems.resourceItem[CountrycheckQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="国家检验信息" />
            <lang locale="zh_HK" value="國家檢驗信息" />
            <lang locale="zh_TW" value="國家檢驗信息" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.foodtrac.client.FoodtracResource].resourceItems.resourceItem[LeavecheckQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="出厂检验信息" />
            <lang locale="zh_HK" value="出廠檢驗信息" />
            <lang locale="zh_TW" value="出廠檢驗信息" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.foodtrac.client.FoodtracResource].resourceItems.resourceItem[ProcesstechQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="加工工艺" />
            <lang locale="zh_HK" value="加工工藝" />
            <lang locale="zh_TW" value="加工工藝" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.foodtrac.client.FoodtracResource].resourceItems.resourceItem[ProductCategoryInfoQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="产品类别信息" />
            <lang locale="zh_HK" value="產品類別信息" />
            <lang locale="zh_TW" value="產品類別信息" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.foodtrac.client.FoodtracResource].resourceItems.resourceItem[RawmaterialinfoQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="原料信息" />
            <lang locale="zh_HK" value="原料信息" />
            <lang locale="zh_TW" value="原料信息" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.foodtrac.client.FoodtracResource].resourceItems.resourceItem[ThirdpartycheckQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="第三方检验信息" />
            <lang locale="zh_HK" value="第三方檢驗信息" />
            <lang locale="zh_TW" value="第三方檢驗信息" />
        </rs>
    </resource>
</i18nResource>

