<?xml version="1.0" encoding="UTF-8"?>
<i18nResource xmlns="com.kingdee.bos.metadata">
    <package>com.kingdee.eas.bdm.bdapply.client</package>
    <name>BdapplyResource</name>
    <alias>i18nResource[com.kingdee.eas.bdm.bdapply.client.BdapplyResource].alias</alias>
    <description>i18nResource[com.kingdee.eas.bdm.bdapply.client.BdapplyResource].description</description>
    <userDefined>true</userDefined>
    <className>com.kingdee.eas.bdm.bdapply.client.BdapplyResource</className>
    <resourceItems>
        <resourceItem>
            <name>SupplierReqQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.bdm.bdapply.client.BdapplyResource].resourceItems.resourceItem[SupplierReqQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CustomerInfoReqQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.bdm.bdapply.client.BdapplyResource].resourceItems.resourceItem[CustomerInfoReqQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>MaterialInfoReqQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.bdm.bdapply.client.BdapplyResource].resourceItems.resourceItem[MaterialInfoReqQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>UserReqQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.bdm.bdapply.client.BdapplyResource].resourceItems.resourceItem[UserReqQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
    </resourceItems>
    <resource>
        <rs key="i18nResource[com.kingdee.eas.bdm.bdapply.client.BdapplyResource].alias">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.bdm.bdapply.client.BdapplyResource].description">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.bdm.bdapply.client.BdapplyResource].resourceItems.resourceItem[CustomerInfoReqQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="客户资料申请单" />
            <lang locale="zh_HK" value="客戶資料申請單" />
            <lang locale="zh_TW" value="客戶資料申請單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.bdm.bdapply.client.BdapplyResource].resourceItems.resourceItem[MaterialInfoReqQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="物料资料申请单" />
            <lang locale="zh_HK" value="物料資料申請單" />
            <lang locale="zh_TW" value="物料資料申請單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.bdm.bdapply.client.BdapplyResource].resourceItems.resourceItem[SupplierReqQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="供应商资料申请单" />
            <lang locale="zh_HK" value="供應商資料申請單" />
            <lang locale="zh_TW" value="供應商資料申請單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.bdm.bdapply.client.BdapplyResource].resourceItems.resourceItem[UserReqQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="用户申请" />
            <lang locale="zh_HK" value="用戶申請" />
            <lang locale="zh_TW" value="用戶申請" />
        </rs>
    </resource>
</i18nResource>

