<?xml version="1.0" encoding="UTF-8"?>
<i18nResource xmlns="com.kingdee.bos.metadata">
    <package>com.kingdee.eas.custom.salepayment.client</package>
    <name>SalepaymentResource</name>
    <alias>i18nResource[com.kingdee.eas.custom.salepayment.client.SalepaymentResource].alias</alias>
    <description>i18nResource[com.kingdee.eas.custom.salepayment.client.SalepaymentResource].description</description>
    <userDefined>true</userDefined>
    <className>com.kingdee.eas.custom.salepayment.client.SalepaymentResource</className>
    <resourceItems>
        <resourceItem>
            <name>SalePaymentSetQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.salepayment.client.SalepaymentResource].resourceItems.resourceItem[SalePaymentSetQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>FeeTypeQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.salepayment.client.SalepaymentResource].resourceItems.resourceItem[FeeTypeQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>ManagerSetQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.salepayment.client.SalepaymentResource].resourceItems.resourceItem[ManagerSetQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>AreaSetQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.salepayment.client.SalepaymentResource].resourceItems.resourceItem[AreaSetQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CompanyTargetQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.salepayment.client.SalepaymentResource].resourceItems.resourceItem[CompanyTargetQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>AreaTargetQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.salepayment.client.SalepaymentResource].resourceItems.resourceItem[AreaTargetQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>SalerStimulateSetQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.salepayment.client.SalepaymentResource].resourceItems.resourceItem[SalerStimulateSetQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>MaterialStandardCostQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.salepayment.client.SalepaymentResource].resourceItems.resourceItem[MaterialStandardCostQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>GrossProfitInfoQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.salepayment.client.SalepaymentResource].resourceItems.resourceItem[GrossProfitInfoQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CustomerSaleTargetQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.salepayment.client.SalepaymentResource].resourceItems.resourceItem[CustomerSaleTargetQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>TechnicianQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.salepayment.client.SalepaymentResource].resourceItems.resourceItem[TechnicianQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>QuarterGrossProfitInfoQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.salepayment.client.SalepaymentResource].resourceItems.resourceItem[QuarterGrossProfitInfoQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>SaleProfitCalculateResultQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.salepayment.client.SalepaymentResource].resourceItems.resourceItem[SaleProfitCalculateResultQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>MonthFeeQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.salepayment.client.SalepaymentResource].resourceItems.resourceItem[MonthFeeQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>SaleFeeInputQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.salepayment.client.SalepaymentResource].resourceItems.resourceItem[SaleFeeInputQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CompanyMonthFeeQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.salepayment.client.SalepaymentResource].resourceItems.resourceItem[CompanyMonthFeeQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>LongTimeArAmountQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.salepayment.client.SalepaymentResource].resourceItems.resourceItem[LongTimeArAmountQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
    </resourceItems>
    <resource>
        <rs key="i18nResource[com.kingdee.eas.custom.salepayment.client.SalepaymentResource].alias">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.salepayment.client.SalepaymentResource].description">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.salepayment.client.SalepaymentResource].resourceItems.resourceItem[AreaSetQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="大区设置" />
            <lang locale="zh_HK" value="大區設置" />
            <lang locale="zh_TW" value="大區設置" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.salepayment.client.SalepaymentResource].resourceItems.resourceItem[AreaTargetQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="大区指标" />
            <lang locale="zh_HK" value="大區指標" />
            <lang locale="zh_TW" value="大區指標" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.salepayment.client.SalepaymentResource].resourceItems.resourceItem[CompanyMonthFeeQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="销售分摊费用" />
            <lang locale="zh_HK" value="銷售分攤費用" />
            <lang locale="zh_TW" value="銷售分攤費用" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.salepayment.client.SalepaymentResource].resourceItems.resourceItem[CompanyTargetQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="公司指标" />
            <lang locale="zh_HK" value="公司指標" />
            <lang locale="zh_TW" value="公司指標" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.salepayment.client.SalepaymentResource].resourceItems.resourceItem[CustomerSaleTargetQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="客户销售指标" />
            <lang locale="zh_HK" value="客戶銷售指標" />
            <lang locale="zh_TW" value="客戶銷售指標" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.salepayment.client.SalepaymentResource].resourceItems.resourceItem[FeeTypeQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="费用类型" />
            <lang locale="zh_HK" value="費用類型" />
            <lang locale="zh_TW" value="費用類型" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.salepayment.client.SalepaymentResource].resourceItems.resourceItem[GrossProfitInfoQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="毛利润计算结果" />
            <lang locale="zh_HK" value="毛利潤計算結果" />
            <lang locale="zh_TW" value="毛利潤計算結果" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.salepayment.client.SalepaymentResource].resourceItems.resourceItem[LongTimeArAmountQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="长期应收款考核" />
            <lang locale="zh_HK" value="長期應收款考核" />
            <lang locale="zh_TW" value="長期應收款考核" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.salepayment.client.SalepaymentResource].resourceItems.resourceItem[ManagerSetQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="大区经理" />
            <lang locale="zh_HK" value="大區經理" />
            <lang locale="zh_TW" value="大區經理" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.salepayment.client.SalepaymentResource].resourceItems.resourceItem[MaterialStandardCostQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="标准成本" />
            <lang locale="zh_HK" value="標準成本" />
            <lang locale="zh_TW" value="標準成本" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.salepayment.client.SalepaymentResource].resourceItems.resourceItem[MonthFeeQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="月费用累计" />
            <lang locale="zh_HK" value="月費用累計" />
            <lang locale="zh_TW" value="月費用累計" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.salepayment.client.SalepaymentResource].resourceItems.resourceItem[QuarterGrossProfitInfoQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="销售指标毛利润计算结果汇总" />
            <lang locale="zh_HK" value="銷售指標毛利潤計算結果匯總" />
            <lang locale="zh_TW" value="銷售指標毛利潤計算結果匯總" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.salepayment.client.SalepaymentResource].resourceItems.resourceItem[SaleFeeInputQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="销售费用录入" />
            <lang locale="zh_HK" value="銷售費用錄入" />
            <lang locale="zh_TW" value="銷售費用錄入" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.salepayment.client.SalepaymentResource].resourceItems.resourceItem[SalePaymentSetQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="公司基础设置" />
            <lang locale="zh_HK" value="公司基礎設置" />
            <lang locale="zh_TW" value="公司基礎設置" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.salepayment.client.SalepaymentResource].resourceItems.resourceItem[SaleProfitCalculateResultQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="销售损益计算结果" />
            <lang locale="zh_HK" value="銷售損益計算結果" />
            <lang locale="zh_TW" value="銷售損益計算結果" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.salepayment.client.SalepaymentResource].resourceItems.resourceItem[SalerStimulateSetQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="销售提成设置" />
            <lang locale="zh_HK" value="銷售提成設置" />
            <lang locale="zh_TW" value="銷售提成設置" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.salepayment.client.SalepaymentResource].resourceItems.resourceItem[TechnicianQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="技术员" />
            <lang locale="zh_HK" value="技術員" />
            <lang locale="zh_TW" value="技術員" />
        </rs>
    </resource>
</i18nResource>

