<?xml version="1.0" encoding="UTF-8"?>
<i18nResource xmlns="com.kingdee.bos.metadata">
    <package>com.kingdee.eas.custom.taihe.contract.client</package>
    <name>ContractResource</name>
    <alias>i18nResource[com.kingdee.eas.custom.taihe.contract.client.ContractResource].alias</alias>
    <description>i18nResource[com.kingdee.eas.custom.taihe.contract.client.ContractResource].description</description>
    <userDefined>true</userDefined>
    <className>com.kingdee.eas.custom.taihe.contract.client.ContractResource</className>
    <resourceItems>
        <resourceItem>
            <name>ContractTypeQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.taihe.contract.client.ContractResource].resourceItems.resourceItem[ContractTypeQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>FarmerQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.taihe.contract.client.ContractResource].resourceItems.resourceItem[FarmerQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>PreBillOfContractQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.taihe.contract.client.ContractResource].resourceItems.resourceItem[PreBillOfContractQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>SuccessiveContractQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.taihe.contract.client.ContractResource].resourceItems.resourceItem[SuccessiveContractQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>BatchContractQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.taihe.contract.client.ContractResource].resourceItems.resourceItem[BatchContractQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>BailAmountQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.taihe.contract.client.ContractResource].resourceItems.resourceItem[BailAmountQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>AssureAmtPolicyQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.taihe.contract.client.ContractResource].resourceItems.resourceItem[AssureAmtPolicyQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>AssureAmtQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.taihe.contract.client.ContractResource].resourceItems.resourceItem[AssureAmtQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
    </resourceItems>
    <resource>
        <rs key="i18nResource[com.kingdee.eas.custom.taihe.contract.client.ContractResource].alias">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.taihe.contract.client.ContractResource].description">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.taihe.contract.client.ContractResource].resourceItems.resourceItem[AssureAmtPolicyQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="保证金政策" />
            <lang locale="zh_HK" value="保證金政策" />
            <lang locale="zh_TW" value="保證金政策" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.taihe.contract.client.ContractResource].resourceItems.resourceItem[AssureAmtQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="保证金" />
            <lang locale="zh_HK" value="保證金" />
            <lang locale="zh_TW" value="保證金" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.taihe.contract.client.ContractResource].resourceItems.resourceItem[BailAmountQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="保证金" />
            <lang locale="zh_HK" value="保證金" />
            <lang locale="zh_TW" value="保證金" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.taihe.contract.client.ContractResource].resourceItems.resourceItem[BatchContractQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="批次合同" />
            <lang locale="zh_HK" value="批次合同" />
            <lang locale="zh_TW" value="批次合同" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.taihe.contract.client.ContractResource].resourceItems.resourceItem[ContractTypeQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="合同类别" />
            <lang locale="zh_HK" value="合同類別" />
            <lang locale="zh_TW" value="合同類別" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.taihe.contract.client.ContractResource].resourceItems.resourceItem[FarmerQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="养殖场" />
            <lang locale="zh_HK" value="養殖場" />
            <lang locale="zh_TW" value="養殖場" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.taihe.contract.client.ContractResource].resourceItems.resourceItem[PreBillOfContractQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="合同预报单" />
            <lang locale="zh_HK" value="合同預報單" />
            <lang locale="zh_TW" value="合同預報單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.taihe.contract.client.ContractResource].resourceItems.resourceItem[SuccessiveContractQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="连养合同" />
            <lang locale="zh_HK" value="連養合同" />
            <lang locale="zh_TW" value="連養合同" />
        </rs>
    </resource>
</i18nResource>

