<?xml version="1.0" encoding="UTF-8"?>
<i18nResource xmlns="com.kingdee.bos.metadata">
    <package>com.kingdee.eas.farm.breed.layegg.client</package>
    <name>LayeggResource</name>
    <alias>i18nResource[com.kingdee.eas.farm.breed.layegg.client.LayeggResource].alias</alias>
    <description>i18nResource[com.kingdee.eas.farm.breed.layegg.client.LayeggResource].description</description>
    <userDefined>true</userDefined>
    <className>com.kingdee.eas.farm.breed.layegg.client.LayeggResource</className>
    <resourceItems>
        <resourceItem>
            <name>LayEggHouseSetQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.breed.layegg.client.LayeggResource].resourceItems.resourceItem[LayEggHouseSetQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>EggConveyorQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.breed.layegg.client.LayeggResource].resourceItems.resourceItem[EggConveyorQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>LayEggDailyQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.breed.layegg.client.LayeggResource].resourceItems.resourceItem[LayEggDailyQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>LayEggBreedModelQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.breed.layegg.client.LayeggResource].resourceItems.resourceItem[LayEggBreedModelQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>LayEggPlanQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.breed.layegg.client.LayeggResource].resourceItems.resourceItem[LayEggPlanQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>ParentDailyQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.breed.layegg.client.LayeggResource].resourceItems.resourceItem[ParentDailyQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>ParentEggDailyQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.breed.layegg.client.LayeggResource].resourceItems.resourceItem[ParentEggDailyQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>LifeFeeQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.breed.layegg.client.LayeggResource].resourceItems.resourceItem[LifeFeeQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
    </resourceItems>
    <resource>
        <rs key="i18nResource[com.kingdee.eas.farm.breed.layegg.client.LayeggResource].alias">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.breed.layegg.client.LayeggResource].description">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.breed.layegg.client.LayeggResource].resourceItems.resourceItem[EggConveyorQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="鸡蛋传送带" />
            <lang locale="zh_HK" value="雞蛋傳送帶" />
            <lang locale="zh_TW" value="雞蛋傳送帶" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.breed.layegg.client.LayeggResource].resourceItems.resourceItem[LayEggBreedModelQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="产蛋饲喂规范" />
            <lang locale="zh_HK" value="產蛋飼喂規範" />
            <lang locale="zh_TW" value="產蛋飼喂規範" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.breed.layegg.client.LayeggResource].resourceItems.resourceItem[LayEggDailyQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="产蛋日报" />
            <lang locale="zh_HK" value="產蛋日報" />
            <lang locale="zh_TW" value="產蛋日報" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.breed.layegg.client.LayeggResource].resourceItems.resourceItem[LayEggHouseSetQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="产蛋鸡舍设置" />
            <lang locale="zh_HK" value="產蛋雞舍設置" />
            <lang locale="zh_TW" value="產蛋雞舍設置" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.breed.layegg.client.LayeggResource].resourceItems.resourceItem[LayEggPlanQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="产蛋计划" />
            <lang locale="zh_HK" value="產蛋計畫" />
            <lang locale="zh_TW" value="產蛋計畫" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.breed.layegg.client.LayeggResource].resourceItems.resourceItem[LifeFeeQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="母鸭生活费" />
            <lang locale="zh_HK" value="母鴨生活費" />
            <lang locale="zh_TW" value="母鴨生活費" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.breed.layegg.client.LayeggResource].resourceItems.resourceItem[ParentDailyQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="种禽养殖日报" />
            <lang locale="zh_HK" value="種禽養殖日報" />
            <lang locale="zh_TW" value="種禽養殖日報" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.breed.layegg.client.LayeggResource].resourceItems.resourceItem[ParentEggDailyQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="种禽日报" />
            <lang locale="zh_HK" value="種禽日報" />
            <lang locale="zh_TW" value="種禽日報" />
        </rs>
    </resource>
</i18nResource>

