<?xml version="1.0" encoding="UTF-8"?>
<i18nResource xmlns="com.kingdee.bos.metadata">
    <package>com.kingdee.eas.farm.carnivorous.feedbiz.client</package>
    <name>FeedbizResource</name>
    <alias>i18nResource[com.kingdee.eas.farm.carnivorous.feedbiz.client.FeedbizResource].alias</alias>
    <description>i18nResource[com.kingdee.eas.farm.carnivorous.feedbiz.client.FeedbizResource].description</description>
    <userDefined>false</userDefined>
    <className>com.kingdee.eas.farm.carnivorous.feedbiz.client.FeedbizResource</className>
    <resourceItems>
        <resourceItem>
            <name>BatchContractQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.feedbiz.client.FeedbizResource].resourceItems.resourceItem[BatchContractQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>BatchQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.feedbiz.client.FeedbizResource].resourceItems.resourceItem[BatchQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>BreedSeedReceiveBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.feedbiz.client.FeedbizResource].resourceItems.resourceItem[BreedSeedReceiveBillQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>FodderReceiveBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.feedbiz.client.FeedbizResource].resourceItems.resourceItem[FodderReceiveBillQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>DrugReceiveBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.feedbiz.client.FeedbizResource].resourceItems.resourceItem[DrugReceiveBillQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>FodderReceptionQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.feedbiz.client.FeedbizResource].resourceItems.resourceItem[FodderReceptionQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>BatchContractBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.feedbiz.client.FeedbizResource].resourceItems.resourceItem[BatchContractBillQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CarnivsSettleBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.feedbiz.client.FeedbizResource].resourceItems.resourceItem[CarnivsSettleBillQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>StockingDailyQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.feedbiz.client.FeedbizResource].resourceItems.resourceItem[StockingDailyQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>BreedDailyQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.feedbiz.client.FeedbizResource].resourceItems.resourceItem[BreedDailyQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>ConFeedContractQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.feedbiz.client.FeedbizResource].resourceItems.resourceItem[ConFeedContractQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CTransFodderBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.feedbiz.client.FeedbizResource].resourceItems.resourceItem[CTransFodderBillQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CTransDrugBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.feedbiz.client.FeedbizResource].resourceItems.resourceItem[CTransDrugBillQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>TransDrugBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.feedbiz.client.FeedbizResource].resourceItems.resourceItem[TransDrugBillQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>DrugApplyBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.feedbiz.client.FeedbizResource].resourceItems.resourceItem[DrugApplyBillQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
    </resourceItems>
    <resource>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.feedbiz.client.FeedbizResource].alias">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.feedbiz.client.FeedbizResource].description">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.feedbiz.client.FeedbizResource].resourceItems.resourceItem[BatchContractBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="批次合同" />
            <lang locale="zh_HK" value="批次合同" />
            <lang locale="zh_TW" value="批次合同" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.feedbiz.client.FeedbizResource].resourceItems.resourceItem[BatchContractQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="批次合同" />
            <lang locale="zh_HK" value="批次合同" />
            <lang locale="zh_TW" value="批次合同" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.feedbiz.client.FeedbizResource].resourceItems.resourceItem[BatchQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="批次信息" />
            <lang locale="zh_HK" value="批次信息" />
            <lang locale="zh_TW" value="批次信息" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.feedbiz.client.FeedbizResource].resourceItems.resourceItem[BreedDailyQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="饲养日报" />
            <lang locale="zh_HK" value="飼養日報" />
            <lang locale="zh_TW" value="飼養日報" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.feedbiz.client.FeedbizResource].resourceItems.resourceItem[BreedSeedReceiveBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="雏苗领用单" />
            <lang locale="zh_HK" value="雛苗領用單" />
            <lang locale="zh_TW" value="雛苗領用單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.feedbiz.client.FeedbizResource].resourceItems.resourceItem[CTransDrugBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="药品调整单" />
            <lang locale="zh_HK" value="藥品調整單" />
            <lang locale="zh_TW" value="藥品調整單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.feedbiz.client.FeedbizResource].resourceItems.resourceItem[CTransFodderBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="调料单" />
            <lang locale="zh_HK" value="調料單" />
            <lang locale="zh_TW" value="調料單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.feedbiz.client.FeedbizResource].resourceItems.resourceItem[CarnivsSettleBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="结算单" />
            <lang locale="zh_HK" value="結算單" />
            <lang locale="zh_TW" value="結算單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.feedbiz.client.FeedbizResource].resourceItems.resourceItem[ConFeedContractQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="连养合同" />
            <lang locale="zh_HK" value="連養合同" />
            <lang locale="zh_TW" value="連養合同" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.feedbiz.client.FeedbizResource].resourceItems.resourceItem[DrugApplyBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="用药申请单" />
            <lang locale="zh_HK" value="用藥申請單" />
            <lang locale="zh_TW" value="用藥申請單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.feedbiz.client.FeedbizResource].resourceItems.resourceItem[DrugReceiveBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="药品处方单" />
            <lang locale="zh_HK" value="藥品處方單" />
            <lang locale="zh_TW" value="藥品處方單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.feedbiz.client.FeedbizResource].resourceItems.resourceItem[FodderReceiveBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="饲料领用单" />
            <lang locale="zh_HK" value="飼料領用單" />
            <lang locale="zh_TW" value="飼料領用單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.feedbiz.client.FeedbizResource].resourceItems.resourceItem[FodderReceptionQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="饲料领用单" />
            <lang locale="zh_HK" value="飼料領用單" />
            <lang locale="zh_TW" value="飼料領用單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.feedbiz.client.FeedbizResource].resourceItems.resourceItem[StockingDailyQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="养殖日报" />
            <lang locale="zh_HK" value="養殖日報" />
            <lang locale="zh_TW" value="養殖日報" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.feedbiz.client.FeedbizResource].resourceItems.resourceItem[TransDrugBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="药品调整单" />
            <lang locale="zh_HK" value="藥品調整單" />
            <lang locale="zh_TW" value="藥品調整單" />
        </rs>
    </resource>
</i18nResource>

