<?xml version="1.0" encoding="UTF-8"?>
<i18nResource xmlns="com.kingdee.bos.metadata">
    <package>com.kingdee.eas.farm.carnivorous.recyclebiz.client</package>
    <name>RecyclebizResource</name>
    <alias>i18nResource[com.kingdee.eas.farm.carnivorous.recyclebiz.client.RecyclebizResource].alias</alias>
    <description>i18nResource[com.kingdee.eas.farm.carnivorous.recyclebiz.client.RecyclebizResource].description</description>
    <userDefined>false</userDefined>
    <className>com.kingdee.eas.farm.carnivorous.recyclebiz.client.RecyclebizResource</className>
    <resourceItems>
        <resourceItem>
            <name>LiveBirdWgtBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.recyclebiz.client.RecyclebizResource].resourceItems.resourceItem[LiveBirdWgtBillQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CarSendBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.recyclebiz.client.RecyclebizResource].resourceItems.resourceItem[CarSendBillQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>DispatchbillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.recyclebiz.client.RecyclebizResource].resourceItems.resourceItem[DispatchbillQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>SendCarBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.recyclebiz.client.RecyclebizResource].resourceItems.resourceItem[SendCarBillQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>DkSettleBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.recyclebiz.client.RecyclebizResource].resourceItems.resourceItem[DkSettleBillQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>ChickenRecBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.recyclebiz.client.RecyclebizResource].resourceItems.resourceItem[ChickenRecBillQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CCarSendBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.recyclebiz.client.RecyclebizResource].resourceItems.resourceItem[CCarSendBillQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>PreHouseWgtBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.recyclebiz.client.RecyclebizResource].resourceItems.resourceItem[PreHouseWgtBillQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CSlaughterBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.recyclebiz.client.RecyclebizResource].resourceItems.resourceItem[CSlaughterBillQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CKSettleBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.recyclebiz.client.RecyclebizResource].resourceItems.resourceItem[CKSettleBillQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>SettleBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.recyclebiz.client.RecyclebizResource].resourceItems.resourceItem[SettleBillQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CKCostAllocateBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.recyclebiz.client.RecyclebizResource].resourceItems.resourceItem[CKCostAllocateBillQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CKPECostbillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.recyclebiz.client.RecyclebizResource].resourceItems.resourceItem[CKPECostbillQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CKWeightBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.recyclebiz.client.RecyclebizResource].resourceItems.resourceItem[CKWeightBillQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
    </resourceItems>
    <resource>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.recyclebiz.client.RecyclebizResource].alias">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.recyclebiz.client.RecyclebizResource].description">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.recyclebiz.client.RecyclebizResource].resourceItems.resourceItem[CCarSendBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="毛鸡派车单" />
            <lang locale="zh_HK" value="毛雞派車單" />
            <lang locale="zh_TW" value="毛雞派車單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.recyclebiz.client.RecyclebizResource].resourceItems.resourceItem[CKCostAllocateBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="费用分摊" />
            <lang locale="zh_HK" value="費用分攤" />
            <lang locale="zh_TW" value="費用分攤" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.recyclebiz.client.RecyclebizResource].resourceItems.resourceItem[CKPECostbillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="暂估成本表" />
            <lang locale="zh_HK" value="暫估成本表" />
            <lang locale="zh_TW" value="暫估成本表" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.recyclebiz.client.RecyclebizResource].resourceItems.resourceItem[CKSettleBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="结算单" />
            <lang locale="zh_HK" value="結算單" />
            <lang locale="zh_TW" value="結算單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.recyclebiz.client.RecyclebizResource].resourceItems.resourceItem[CKWeightBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="公司过磅单" />
            <lang locale="zh_HK" value="公司過磅單" />
            <lang locale="zh_TW" value="公司過磅單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.recyclebiz.client.RecyclebizResource].resourceItems.resourceItem[CSlaughterBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="屠宰单" />
            <lang locale="zh_HK" value="屠宰單" />
            <lang locale="zh_TW" value="屠宰單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.recyclebiz.client.RecyclebizResource].resourceItems.resourceItem[CarSendBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="派车单" />
            <lang locale="zh_HK" value="派車單" />
            <lang locale="zh_TW" value="派車單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.recyclebiz.client.RecyclebizResource].resourceItems.resourceItem[ChickenRecBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="毛鸡回收订单" />
            <lang locale="zh_HK" value="毛雞回收訂單" />
            <lang locale="zh_TW" value="毛雞回收訂單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.recyclebiz.client.RecyclebizResource].resourceItems.resourceItem[DispatchbillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="派车单" />
            <lang locale="zh_HK" value="派車單" />
            <lang locale="zh_TW" value="派車單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.recyclebiz.client.RecyclebizResource].resourceItems.resourceItem[DkSettleBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="结算单" />
            <lang locale="zh_HK" value="結算單" />
            <lang locale="zh_TW" value="結算單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.recyclebiz.client.RecyclebizResource].resourceItems.resourceItem[LiveBirdWgtBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="活禽过磅单" />
            <lang locale="zh_HK" value="活禽過磅單" />
            <lang locale="zh_TW" value="活禽過磅單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.recyclebiz.client.RecyclebizResource].resourceItems.resourceItem[PreHouseWgtBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="棚前过磅单" />
            <lang locale="zh_HK" value="棚前過磅單" />
            <lang locale="zh_TW" value="棚前過磅單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.recyclebiz.client.RecyclebizResource].resourceItems.resourceItem[SendCarBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="派车单" />
            <lang locale="zh_HK" value="派車單" />
            <lang locale="zh_TW" value="派車單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.recyclebiz.client.RecyclebizResource].resourceItems.resourceItem[SettleBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="结算单" />
            <lang locale="zh_HK" value="結算單" />
            <lang locale="zh_TW" value="結算單" />
        </rs>
    </resource>
</i18nResource>

