<?xml version="1.0" encoding="UTF-8"?>
<i18nResource xmlns="com.kingdee.bos.metadata">
    <package>com.kingdee.eas.farm.carnivorous.basedata.client</package>
    <name>BasedataResource</name>
    <alias>i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].alias</alias>
    <description>i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].description</description>
    <userDefined>true</userDefined>
    <className>com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource</className>
    <resourceItems>
        <resourceItem>
            <name>FarmerQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[FarmerQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>FarmQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[FarmQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>SystemSettingQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[SystemSettingQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>BatchContractQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[BatchContractQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>BatchQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[BatchQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>PersonFarmerRelationQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[PersonFarmerRelationQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>PersonFarmerRangeQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[PersonFarmerRangeQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>SettlePolicyQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[SettlePolicyQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>DrugCostQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[DrugCostQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>FodderCostQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[FodderCostQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>BreedSeedCostQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[BreedSeedCostQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>BreedSeedPriceQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[BreedSeedPriceQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>FodderPriceQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[FodderPriceQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>FreightBaseQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[FreightBaseQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>FeedStdQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[FeedStdQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>YieldDataBaseQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[YieldDataBaseQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>InvestmentPolicyQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[InvestmentPolicyQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>SettleDataBaseQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[SettleDataBaseQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>RoadLineQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[RoadLineQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>MarketSettlePolicyQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[MarketSettlePolicyQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>MarketPolicyQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[MarketPolicyQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>MarginPolicyQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[MarginPolicyQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>ConFeedPolicyQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[ConFeedPolicyQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>SubsidyPolicyQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[SubsidyPolicyQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>FarmerTypeQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[FarmerTypeQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CustomerViewTypeQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[CustomerViewTypeQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>RewardAndPunishItemQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[RewardAndPunishItemQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>DailyOutSaleCPriceQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[DailyOutSaleCPriceQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>RanPPolicyQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[RanPPolicyQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>RandPPolicyQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[RandPPolicyQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>TempPolicyQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[TempPolicyQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CKDressingPercentQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[CKDressingPercentQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>FarmingCheckItemQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[FarmingCheckItemQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>FreightCalPointQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[FreightCalPointQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>FodderStdQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[FodderStdQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>InputSeedPlanQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[InputSeedPlanQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CatchCKTeamQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[CatchCKTeamQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>VetQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[VetQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>AvgWgtSectionQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[AvgWgtSectionQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>BatchRelationQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[BatchRelationQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CarviousFeedComMeatQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[CarviousFeedComMeatQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>BrowerItemQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[BrowerItemQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>BorrowDayRateQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[BorrowDayRateQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>FarmerBorrowQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[FarmerBorrowQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>BrowerItemNewQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[BrowerItemNewQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>BorrowItemReturnQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[BorrowItemReturnQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>MarginGetPolicyQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[MarginGetPolicyQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>MarginBorrowPolicyQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[MarginBorrowPolicyQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>MarginBreedPolicyQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[MarginBreedPolicyQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>FarmerBorrowNewQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[FarmerBorrowNewQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>InvestmentPolicyChickenQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[InvestmentPolicyChickenQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
    </resourceItems>
    <resource>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].alias">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].description">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[AvgWgtSectionQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="均重区间表" />
            <lang locale="zh_HK" value="均重區間表" />
            <lang locale="zh_TW" value="均重區間表" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[BatchContractQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="批次合同" />
            <lang locale="zh_HK" value="批次合同" />
            <lang locale="zh_TW" value="批次合同" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[BatchQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="批次信息" />
            <lang locale="zh_HK" value="批次信息" />
            <lang locale="zh_TW" value="批次信息" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[BatchRelationQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="种鸡批次关联关系" />
            <lang locale="zh_HK" value="種雞批次關聯關係" />
            <lang locale="zh_TW" value="種雞批次關聯關係" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[BorrowDayRateQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="借款项目日利率" />
            <lang locale="zh_HK" value="借款項目日利率" />
            <lang locale="zh_TW" value="借款項目日利率" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[BorrowItemReturnQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="借款项目还款标准" />
            <lang locale="zh_HK" value="借款項目還款標準" />
            <lang locale="zh_TW" value="借款項目還款標準" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[BreedSeedCostQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="雏苗成本" />
            <lang locale="zh_HK" value="雛苗成本" />
            <lang locale="zh_TW" value="雛苗成本" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[BreedSeedPriceQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="雏苗价格维护" />
            <lang locale="zh_HK" value="雛苗價格維護" />
            <lang locale="zh_TW" value="雛苗價格維護" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[BrowerItemNewQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="借款项目" />
            <lang locale="zh_HK" value="借款項目" />
            <lang locale="zh_TW" value="借款項目" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[BrowerItemQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="借款项目" />
            <lang locale="zh_HK" value="借款項目" />
            <lang locale="zh_TW" value="借款項目" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[CKDressingPercentQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="出肉率系数表" />
            <lang locale="zh_HK" value="出肉率係數表" />
            <lang locale="zh_TW" value="出肉率係數表" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[CarviousFeedComMeatQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="商品代料肉比标准" />
            <lang locale="zh_HK" value="商品代料肉比標準" />
            <lang locale="zh_TW" value="商品代料肉比標準" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[CatchCKTeamQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="抓鸡队" />
            <lang locale="zh_HK" value="抓雞隊" />
            <lang locale="zh_TW" value="抓雞隊" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[ConFeedPolicyQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="连养政策" />
            <lang locale="zh_HK" value="連養政策" />
            <lang locale="zh_TW" value="連養政策" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[CustomerViewTypeQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="客诉类型" />
            <lang locale="zh_HK" value="客訴類型" />
            <lang locale="zh_TW" value="客訴類型" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[DailyOutSaleCPriceQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="外卖毛鸡价格单" />
            <lang locale="zh_HK" value="外賣毛雞價格單" />
            <lang locale="zh_TW" value="外賣毛雞價格單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[DrugCostQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="药品成本" />
            <lang locale="zh_HK" value="藥品成本" />
            <lang locale="zh_TW" value="藥品成本" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[FarmQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="养殖场" />
            <lang locale="zh_HK" value="養殖場" />
            <lang locale="zh_TW" value="養殖場" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[FarmerBorrowNewQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="养殖户借款单" />
            <lang locale="zh_HK" value="養殖戶借款單" />
            <lang locale="zh_TW" value="養殖戶借款單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[FarmerBorrowQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="养殖户借款单" />
            <lang locale="zh_HK" value="養殖戶借款單" />
            <lang locale="zh_TW" value="養殖戶借款單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[FarmerQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="养殖户" />
            <lang locale="zh_HK" value="養殖戶" />
            <lang locale="zh_TW" value="養殖戶" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[FarmerTypeQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="养殖户类别" />
            <lang locale="zh_HK" value="養殖戶類別" />
            <lang locale="zh_TW" value="養殖戶類別" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[FarmingCheckItemQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="评定项目" />
            <lang locale="zh_HK" value="評定項目" />
            <lang locale="zh_TW" value="評定項目" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[FeedStdQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="饲喂标准" />
            <lang locale="zh_HK" value="飼喂標準" />
            <lang locale="zh_TW" value="飼喂標準" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[FodderCostQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="饲料成本" />
            <lang locale="zh_HK" value="飼料成本" />
            <lang locale="zh_TW" value="飼料成本" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[FodderPriceQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="饲料价格" />
            <lang locale="zh_HK" value="飼料價格" />
            <lang locale="zh_TW" value="飼料價格" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[FodderStdQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="饲料标准耗用表" />
            <lang locale="zh_HK" value="飼料標準耗用表" />
            <lang locale="zh_TW" value="飼料標準耗用表" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[FreightBaseQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="运费基础资料" />
            <lang locale="zh_HK" value="運費基礎資料" />
            <lang locale="zh_TW" value="運費基礎資料" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[FreightCalPointQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="运费计算点" />
            <lang locale="zh_HK" value="運費計算點" />
            <lang locale="zh_TW" value="運費計算點" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[InputSeedPlanQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="放养计划表" />
            <lang locale="zh_HK" value="放養計畫表" />
            <lang locale="zh_TW" value="放養計畫表" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[InvestmentPolicyChickenQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="鸡雏投入政策" />
            <lang locale="zh_HK" value="雞雛投入政策" />
            <lang locale="zh_TW" value="雞雛投入政策" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[InvestmentPolicyQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="投入政策" />
            <lang locale="zh_HK" value="投入政策" />
            <lang locale="zh_TW" value="投入政策" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[MarginBorrowPolicyQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="保证金借取政策" />
            <lang locale="zh_HK" value="保證金借取政策" />
            <lang locale="zh_TW" value="保證金借取政策" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[MarginBreedPolicyQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="保证金雏苗让利政策" />
            <lang locale="zh_HK" value="保證金雛苗讓利政策" />
            <lang locale="zh_TW" value="保證金雛苗讓利政策" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[MarginGetPolicyQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="保证金留取政策" />
            <lang locale="zh_HK" value="保證金留取政策" />
            <lang locale="zh_TW" value="保證金留取政策" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[MarginPolicyQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="保证金政策" />
            <lang locale="zh_HK" value="保證金政策" />
            <lang locale="zh_TW" value="保證金政策" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[MarketPolicyQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="市场结算政策" />
            <lang locale="zh_HK" value="市場結算政策" />
            <lang locale="zh_TW" value="市場結算政策" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[MarketSettlePolicyQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="市场结算政策" />
            <lang locale="zh_HK" value="市場結算政策" />
            <lang locale="zh_TW" value="市場結算政策" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[PersonFarmerRangeQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="技术员养户范围" />
            <lang locale="zh_HK" value="技術員養戶範圍" />
            <lang locale="zh_TW" value="技術員養戶範圍" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[PersonFarmerRelationQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="技术员养护范围" />
            <lang locale="zh_HK" value="技術員養護範圍" />
            <lang locale="zh_TW" value="技術員養護範圍" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[RanPPolicyQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="奖惩政策" />
            <lang locale="zh_HK" value="獎懲政策" />
            <lang locale="zh_TW" value="獎懲政策" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[RandPPolicyQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="奖惩政策" />
            <lang locale="zh_HK" value="獎懲政策" />
            <lang locale="zh_TW" value="獎懲政策" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[RewardAndPunishItemQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="奖惩项目" />
            <lang locale="zh_HK" value="獎懲項目" />
            <lang locale="zh_TW" value="獎懲項目" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[RoadLineQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="线路" />
            <lang locale="zh_HK" value="線路" />
            <lang locale="zh_TW" value="線路" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[SettleDataBaseQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="结算基础资料设置" />
            <lang locale="zh_HK" value="結算基礎資料設置" />
            <lang locale="zh_TW" value="結算基礎資料設置" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[SettlePolicyQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="结算政策" />
            <lang locale="zh_HK" value="結算政策" />
            <lang locale="zh_TW" value="結算政策" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[SubsidyPolicyQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="补贴政策" />
            <lang locale="zh_HK" value="補貼政策" />
            <lang locale="zh_TW" value="補貼政策" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[SystemSettingQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="系统设置" />
            <lang locale="zh_HK" value="系統設置" />
            <lang locale="zh_TW" value="系統設置" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[TempPolicyQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="临时政策" />
            <lang locale="zh_HK" value="臨時政策" />
            <lang locale="zh_TW" value="臨時政策" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[VetQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="兽医" />
            <lang locale="zh_HK" value="獸醫" />
            <lang locale="zh_TW" value="獸醫" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.basedata.client.BasedataResource].resourceItems.resourceItem[YieldDataBaseQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="出成率设置" />
            <lang locale="zh_HK" value="出成率設置" />
            <lang locale="zh_TW" value="出成率設置" />
        </rs>
    </resource>
</i18nResource>

