<?xml version="1.0" encoding="UTF-8"?>
<i18nResource xmlns="com.kingdee.bos.metadata">
    <package>com.kingdee.eas.custom.taihe.server.client</package>
    <name>ServerResource</name>
    <alias>i18nResource[com.kingdee.eas.custom.taihe.server.client.ServerResource].alias</alias>
    <description>i18nResource[com.kingdee.eas.custom.taihe.server.client.ServerResource].description</description>
    <userDefined>false</userDefined>
    <className>com.kingdee.eas.custom.taihe.server.client.ServerResource</className>
    <resourceItems>
        <resourceItem>
            <name>ReturnBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.taihe.server.client.ServerResource].resourceItems.resourceItem[ReturnBillQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
    </resourceItems>
    <resource>
        <rs key="i18nResource[com.kingdee.eas.custom.taihe.server.client.ServerResource].alias">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.taihe.server.client.ServerResource].description">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.taihe.server.client.ServerResource].resourceItems.resourceItem[ReturnBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="回访单" />
            <lang locale="zh_HK" value="回訪單" />
            <lang locale="zh_TW" value="回訪單" />
        </rs>
    </resource>
</i18nResource>

