<?xml version="1.0" encoding="UTF-8"?>
<i18nResource xmlns="com.kingdee.bos.metadata">
    <package>com.kingdee.eas.custom.salediscount.client</package>
    <name>DiscountSet</name>
    <alias>i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].alias</alias>
    <description>i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].description</description>
    <userDefined>true</userDefined>
    <className>com.kingdee.eas.custom.salediscount.client.DiscountSet</className>
    <resourceItems>
        <resourceItem>
            <name>auditAlert</name>
            <value>i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[auditAlert].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>unauditAlert</name>
            <value>i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[unauditAlert].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>blockAlert</name>
            <value>i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[blockAlert].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>unblockAlert</name>
            <value>i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[unblockAlert].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>auditSuccess</name>
            <value>i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[auditSuccess].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>unauditSuccess</name>
            <value>i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[unauditSuccess].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>blockSuccess</name>
            <value>i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[blockSuccess].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>unblockSuccess</name>
            <value>i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[unblockSuccess].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>auditEntries</name>
            <value>i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[auditEntries].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>auditEntriesTooltip</name>
            <value>i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[auditEntriesTooltip].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>unAuditEntries</name>
            <value>i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[unAuditEntries].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>unAuditEntriesTooltip</name>
            <value>i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[unAuditEntriesTooltip].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>audit</name>
            <value>i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[audit].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>auditTooltip</name>
            <value>i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[auditTooltip].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>unAudit</name>
            <value>i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[unAudit].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>unAuditTooltip</name>
            <value>i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[unAuditTooltip].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>blocked</name>
            <value>i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[blocked].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>blockedTooltip</name>
            <value>i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[blockedTooltip].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>unBlocked</name>
            <value>i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[unBlocked].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>unBlockedTooltip</name>
            <value>i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[unBlockedTooltip].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>copyEntries</name>
            <value>i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[copyEntries].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>copyEntriesTooltip</name>
            <value>i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[copyEntriesTooltip].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>copyEntriesAlert</name>
            <value>i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[copyEntriesAlert].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>cannotEdit</name>
            <value>i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[cannotEdit].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>customer</name>
            <value>i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[customer].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>material</name>
            <value>i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[material].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>policycannotaudit</name>
            <value>i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[policycannotaudit].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>policycannotunaudit</name>
            <value>i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[policycannotunaudit].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>auditcannotedit</name>
            <value>i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[auditcannotedit].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>sltcustomer</name>
            <value>i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[sltcustomer].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>sltCustomerGroup</name>
            <value>i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[sltCustomerGroup].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>sltMaterial</name>
            <value>i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[sltMaterial].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>sltMaterialGroup</name>
            <value>i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[sltMaterialGroup].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>auditcannotDel</name>
            <value>i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[auditcannotDel].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>setassistproperty</name>
            <value>i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[setassistproperty].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>selectchildnode</name>
            <value>i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[selectchildnode].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>customerGroup</name>
            <value>i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[customerGroup].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>materialGroup</name>
            <value>i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[materialGroup].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>pricePolicy</name>
            <value>i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[pricePolicy].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CUHASNOBASEPRICE</name>
            <value>i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[CUHASNOBASEPRICE].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>ROWNO</name>
            <value>i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[ROWNO].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>HASNOBASEPRICE</name>
            <value>i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[HASNOBASEPRICE].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>COLNO</name>
            <value>i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[COLNO].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
    </resourceItems>
    <resource>
        <rs key="i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].alias">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="价格政策" />
            <lang locale="zh_TW" value="價格政策" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].description">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[COLNO].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="行" />
            <lang locale="zh_TW" value="行" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[CUHASNOBASEPRICE].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="当前销售组织所属的管理单元没有基本价格！" />
            <lang locale="zh_TW" value="當前銷售組織所屬的管理單元沒有基本價格！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[HASNOBASEPRICE].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="行的物料在当前销售组织所在的管理单元没有定义基本价格！" />
            <lang locale="zh_TW" value="行的物料在當前銷售組織所在的管理單元沒有定義基本價格！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[ROWNO].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="第" />
            <lang locale="zh_TW" value="第" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[auditAlert].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="是否对选择的记录行进行审核?" />
            <lang locale="zh_TW" value="是否對選擇的記錄行進行審核?" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[auditEntriesTooltip].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="审核分录" />
            <lang locale="zh_TW" value="審核分錄" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[auditEntries].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="审核分录" />
            <lang locale="zh_TW" value="審核分錄" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[auditSuccess].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="审核成功!" />
            <lang locale="zh_TW" value="審核成功!" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[auditTooltip].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="审核" />
            <lang locale="zh_TW" value="審核" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[audit].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="审核" />
            <lang locale="zh_TW" value="審核" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[auditcannotDel].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="禁用或审核的价格政策不能删除，请重新选择。" />
            <lang locale="zh_TW" value="禁用或審核的價格政策不能刪除，請重新選擇。" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[auditcannotedit].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="禁用或审核的价格政策不能修改，请重新选择。" />
            <lang locale="zh_TW" value="禁用或審核的價格政策不能修改，請重新選擇。" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[blockAlert].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="是否对选择的记录行进行禁用?" />
            <lang locale="zh_TW" value="是否對選擇的記錄行進行禁用?" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[blockSuccess].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="禁用成功!" />
            <lang locale="zh_TW" value="禁用成功!" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[blockedTooltip].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="禁用" />
            <lang locale="zh_TW" value="禁用" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[blocked].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="禁用" />
            <lang locale="zh_TW" value="禁用" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[cannotEdit].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="禁用或审核的价格政策不能修改，请重新选择。" />
            <lang locale="zh_TW" value="禁用或審核的價格政策不能修改，請重新選擇。" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[copyEntriesAlert].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="是否复制选择的分录？" />
            <lang locale="zh_TW" value="是否複製選擇的分錄？" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[copyEntriesTooltip].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="复制分录" />
            <lang locale="zh_TW" value="複製分錄" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[copyEntries].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="复制分录" />
            <lang locale="zh_TW" value="複製分錄" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[customerGroup].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="客户分类" />
            <lang locale="zh_TW" value="客戶分類" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[customer].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="客户" />
            <lang locale="zh_TW" value="客戶" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[materialGroup].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="物料分类" />
            <lang locale="zh_TW" value="物料分類" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[material].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="物料" />
            <lang locale="zh_TW" value="物料" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[policycannotaudit].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="政策还没有保存，不能审核." />
            <lang locale="zh_TW" value="政策還沒有保存，不能審核." />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[policycannotunaudit].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="政策还没有保存，不能反审核" />
            <lang locale="zh_TW" value="政策還沒有保存，不能反審核" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[pricePolicy].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="价格政策" />
            <lang locale="zh_TW" value="價格政策" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[selectchildnode].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="不能选择根节点修改物料，请在左边的树中选择对应的节点。" />
            <lang locale="zh_TW" value="不能選擇根節點修改物料，請在左邊的樹中選擇對應的節點。" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[setassistproperty].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="请选择辅助属性。" />
            <lang locale="zh_TW" value="請選擇輔助屬性。" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[sltCustomerGroup].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="价格组合中第一位是客户分类，请在左边的客户树中选择一客户分类。" />
            <lang locale="zh_TW" value="價格組合中第一位是客戶分類，請在左邊的客戶樹中選擇一客戶分類。" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[sltMaterialGroup].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="价格组合中第一位是物料组，请在左边的物料树中选择一物料组。" />
            <lang locale="zh_TW" value="價格組合中第一位是物料組，請在左邊的物料樹中選擇一物料組。" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[sltMaterial].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="价格组合中第一位是物料，请在左边的物料树中选择一物料。" />
            <lang locale="zh_TW" value="價格組合中第一位是物料，請在左邊的物料樹中選擇一物料。" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[sltcustomer].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="价格组合中第一位是客户，请在左边的客户树中选择一客户。" />
            <lang locale="zh_TW" value="價格組合中第一位是客戶，請在左邊的客戶樹中選擇一客戶。" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[unAuditEntriesTooltip].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="反审核分录" />
            <lang locale="zh_TW" value="反審核分錄" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[unAuditEntries].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="反审核分录" />
            <lang locale="zh_TW" value="反審核分錄" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[unAuditTooltip].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="反审核" />
            <lang locale="zh_TW" value="反審核" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[unAudit].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="反审核" />
            <lang locale="zh_TW" value="反審核" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[unBlockedTooltip].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="启用" />
            <lang locale="zh_TW" value="啟用" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[unBlocked].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="启用" />
            <lang locale="zh_TW" value="啟用" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[unauditAlert].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="是否对选择的记录行进行反审核?" />
            <lang locale="zh_TW" value="是否對選擇的記錄行進行反審核?" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[unauditSuccess].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="反审核成功!" />
            <lang locale="zh_TW" value="反審核成功!" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[unblockAlert].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="是否对选择的记录行进行启用?" />
            <lang locale="zh_TW" value="是否對選擇的記錄行進行啟用?" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.salediscount.client.DiscountSet].resourceItems.resourceItem[unblockSuccess].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="启用成功!" />
            <lang locale="zh_TW" value="啟用成功!" />
        </rs>
    </resource>
</i18nResource>

