<?xml version="1.0" encoding="UTF-8"?>
<i18nResource xmlns="com.kingdee.bos.metadata">
    <package>com.kingdee.eas.custom.applicationofsocialsecurity.client</package>
    <name>ApplicationofsocialsecurityResource</name>
    <alias>i18nResource[com.kingdee.eas.custom.applicationofsocialsecurity.client.ApplicationofsocialsecurityResource].alias</alias>
    <description>i18nResource[com.kingdee.eas.custom.applicationofsocialsecurity.client.ApplicationofsocialsecurityResource].description</description>
    <userDefined>false</userDefined>
    <className>com.kingdee.eas.custom.applicationofsocialsecurity.client.ApplicationofsocialsecurityResource</className>
    <resourceItems>
        <resourceItem>
            <name>ApplicationOfSocialSecurityQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.applicationofsocialsecurity.client.ApplicationofsocialsecurityResource].resourceItems.resourceItem[ApplicationOfSocialSecurityQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>PersonTypeQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.applicationofsocialsecurity.client.ApplicationofsocialsecurityResource].resourceItems.resourceItem[PersonTypeQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>DataBaseConnectionQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.applicationofsocialsecurity.client.ApplicationofsocialsecurityResource].resourceItems.resourceItem[DataBaseConnectionQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>ModifySIStatusQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.applicationofsocialsecurity.client.ApplicationofsocialsecurityResource].resourceItems.resourceItem[ModifySIStatusQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
    </resourceItems>
    <resource>
        <rs key="i18nResource[com.kingdee.eas.custom.applicationofsocialsecurity.client.ApplicationofsocialsecurityResource].alias">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.applicationofsocialsecurity.client.ApplicationofsocialsecurityResource].description">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.applicationofsocialsecurity.client.ApplicationofsocialsecurityResource].resourceItems.resourceItem[ApplicationOfSocialSecurityQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="社保申请" />
            <lang locale="zh_HK" value="社保申請" />
            <lang locale="zh_TW" value="社保申請" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.applicationofsocialsecurity.client.ApplicationofsocialsecurityResource].resourceItems.resourceItem[DataBaseConnectionQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="数据库连接设置" />
            <lang locale="zh_HK" value="資料庫連接設置" />
            <lang locale="zh_TW" value="資料庫連接設置" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.applicationofsocialsecurity.client.ApplicationofsocialsecurityResource].resourceItems.resourceItem[ModifySIStatusQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="修改sHR员工社保状态" />
            <lang locale="zh_HK" value="修改sHR員工社保狀態" />
            <lang locale="zh_TW" value="修改sHR員工社保狀態" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.applicationofsocialsecurity.client.ApplicationofsocialsecurityResource].resourceItems.resourceItem[PersonTypeQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="人员类别" />
            <lang locale="zh_HK" value="人員類別" />
            <lang locale="zh_TW" value="人員類別" />
        </rs>
    </resource>
</i18nResource>

