<?xml version="1.0" encoding="UTF-8"?>
<i18nResource xmlns="com.kingdee.bos.metadata">
    <package>com.kingdee.eas.farm.carnivorous.basebiz.client</package>
    <name>BasebizResource</name>
    <alias>i18nResource[com.kingdee.eas.farm.carnivorous.basebiz.client.BasebizResource].alias</alias>
    <description>i18nResource[com.kingdee.eas.farm.carnivorous.basebiz.client.BasebizResource].description</description>
    <userDefined>true</userDefined>
    <className>com.kingdee.eas.farm.carnivorous.basebiz.client.BasebizResource</className>
    <resourceItems>
        <resourceItem>
            <name>FarmerQualicationApplQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.basebiz.client.BasebizResource].resourceItems.resourceItem[FarmerQualicationApplQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>MarginQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.basebiz.client.BasebizResource].resourceItems.resourceItem[MarginQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>MaiginBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.basebiz.client.BasebizResource].resourceItems.resourceItem[MaiginBillQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>MarginInitBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.basebiz.client.BasebizResource].resourceItems.resourceItem[MarginInitBillQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>MarginUnlockBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.basebiz.client.BasebizResource].resourceItems.resourceItem[MarginUnlockBillQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CesQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.basebiz.client.BasebizResource].resourceItems.resourceItem[CesQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CustomerViewReqBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.basebiz.client.BasebizResource].resourceItems.resourceItem[CustomerViewReqBillQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>FarmerGuaranteeBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.carnivorous.basebiz.client.BasebizResource].resourceItems.resourceItem[FarmerGuaranteeBillQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
    </resourceItems>
    <resource>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.basebiz.client.BasebizResource].alias">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.basebiz.client.BasebizResource].description">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.basebiz.client.BasebizResource].resourceItems.resourceItem[CesQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="Ces" />
            <lang locale="zh_HK" value="Ces" />
            <lang locale="zh_TW" value="Ces" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.basebiz.client.BasebizResource].resourceItems.resourceItem[CustomerViewReqBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="客诉申请单" />
            <lang locale="zh_HK" value="客訴申請單" />
            <lang locale="zh_TW" value="客訴申請單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.basebiz.client.BasebizResource].resourceItems.resourceItem[FarmerGuaranteeBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="担保申请单" />
            <lang locale="zh_HK" value="擔保申請單" />
            <lang locale="zh_TW" value="擔保申請單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.basebiz.client.BasebizResource].resourceItems.resourceItem[FarmerQualicationApplQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="养户资格申请" />
            <lang locale="zh_HK" value="養戶資格申請" />
            <lang locale="zh_TW" value="養戶資格申請" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.basebiz.client.BasebizResource].resourceItems.resourceItem[MaiginBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="保证金" />
            <lang locale="zh_HK" value="保證金" />
            <lang locale="zh_TW" value="保證金" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.basebiz.client.BasebizResource].resourceItems.resourceItem[MarginInitBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="保证金初始化单" />
            <lang locale="zh_HK" value="保證金初始化單" />
            <lang locale="zh_TW" value="保證金初始化單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.basebiz.client.BasebizResource].resourceItems.resourceItem[MarginQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="保证金" />
            <lang locale="zh_HK" value="保證金" />
            <lang locale="zh_TW" value="保證金" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.carnivorous.basebiz.client.BasebizResource].resourceItems.resourceItem[MarginUnlockBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="保证金解锁单" />
            <lang locale="zh_HK" value="保證金解鎖單" />
            <lang locale="zh_TW" value="保證金解鎖單" />
        </rs>
    </resource>
</i18nResource>

