<?xml version="1.0" encoding="UTF-8"?>
<i18nResource xmlns="com.kingdee.bos.metadata">
    <package>com.kingdee.eas.farm.breed.brood.client</package>
    <name>BroodResource</name>
    <alias>i18nResource[com.kingdee.eas.farm.breed.brood.client.BroodResource].alias</alias>
    <description>i18nResource[com.kingdee.eas.farm.breed.brood.client.BroodResource].description</description>
    <userDefined>true</userDefined>
    <className>com.kingdee.eas.farm.breed.brood.client.BroodResource</className>
    <resourceItems>
        <resourceItem>
            <name>BroodDailyQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.breed.brood.client.BroodResource].resourceItems.resourceItem[BroodDailyQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>BroodCoopSetQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.breed.brood.client.BroodResource].resourceItems.resourceItem[BroodCoopSetQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
    </resourceItems>
    <resource>
        <rs key="i18nResource[com.kingdee.eas.farm.breed.brood.client.BroodResource].alias">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.breed.brood.client.BroodResource].description">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.breed.brood.client.BroodResource].resourceItems.resourceItem[BroodCoopSetQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="育成鸡舍设置" />
            <lang locale="zh_HK" value="育成雞舍設置" />
            <lang locale="zh_TW" value="育成雞舍設置" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.breed.brood.client.BroodResource].resourceItems.resourceItem[BroodDailyQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="育成日报" />
            <lang locale="zh_HK" value="育成日報" />
            <lang locale="zh_TW" value="育成日報" />
        </rs>
    </resource>
</i18nResource>

