<?xml version="1.0" encoding="UTF-8"?>
<i18nResource xmlns="com.kingdee.bos.metadata">
    <package>com.kingdee.eas.farm.dayratecost.client</package>
    <name>DayratecostResource</name>
    <alias>i18nResource[com.kingdee.eas.farm.dayratecost.client.DayratecostResource].alias</alias>
    <description>i18nResource[com.kingdee.eas.farm.dayratecost.client.DayratecostResource].description</description>
    <userDefined>false</userDefined>
    <className>com.kingdee.eas.farm.dayratecost.client.DayratecostResource</className>
    <resourceItems>
        <resourceItem>
            <name>DayRateBaseSettingQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.dayratecost.client.DayratecostResource].resourceItems.resourceItem[DayRateBaseSettingQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>DayRateCostDetailQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.dayratecost.client.DayratecostResource].resourceItems.resourceItem[DayRateCostDetailQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>DayRateInitBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.dayratecost.client.DayratecostResource].resourceItems.resourceItem[DayRateInitBillQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CostAllocationQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.dayratecost.client.DayratecostResource].resourceItems.resourceItem[CostAllocationQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>DayRateCostPeroidQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.dayratecost.client.DayratecostResource].resourceItems.resourceItem[DayRateCostPeroidQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>DayrateFeeItemQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.dayratecost.client.DayratecostResource].resourceItems.resourceItem[DayrateFeeItemQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>ArAmountOffsetDetailBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.dayratecost.client.DayratecostResource].resourceItems.resourceItem[ArAmountOffsetDetailBillQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
    </resourceItems>
    <resource>
        <rs key="i18nResource[com.kingdee.eas.farm.dayratecost.client.DayratecostResource].alias">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.dayratecost.client.DayratecostResource].description">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.dayratecost.client.DayratecostResource].resourceItems.resourceItem[ArAmountOffsetDetailBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="应收冲减明细" />
            <lang locale="zh_HK" value="應收沖減明細" />
            <lang locale="zh_TW" value="應收沖減明細" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.dayratecost.client.DayratecostResource].resourceItems.resourceItem[CostAllocationQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="费用分摊" />
            <lang locale="zh_HK" value="費用分攤" />
            <lang locale="zh_TW" value="費用分攤" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.dayratecost.client.DayratecostResource].resourceItems.resourceItem[DayRateBaseSettingQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="基础设置" />
            <lang locale="zh_HK" value="基礎設置" />
            <lang locale="zh_TW" value="基礎設置" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.dayratecost.client.DayratecostResource].resourceItems.resourceItem[DayRateCostDetailQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="日成本明细记录" />
            <lang locale="zh_HK" value="日成本明細記錄" />
            <lang locale="zh_TW" value="日成本明細記錄" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.dayratecost.client.DayratecostResource].resourceItems.resourceItem[DayRateCostPeroidQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="期间定义" />
            <lang locale="zh_HK" value="期間定義" />
            <lang locale="zh_TW" value="期間定義" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.dayratecost.client.DayratecostResource].resourceItems.resourceItem[DayRateInitBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="日成本初始化单据" />
            <lang locale="zh_HK" value="日成本初始化單據" />
            <lang locale="zh_TW" value="日成本初始化單據" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.dayratecost.client.DayratecostResource].resourceItems.resourceItem[DayrateFeeItemQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="费用项目" />
            <lang locale="zh_HK" value="費用項目" />
            <lang locale="zh_TW" value="費用項目" />
        </rs>
    </resource>
</i18nResource>

