<?xml version="1.0" encoding="UTF-8"?>
<i18nResource xmlns="com.kingdee.bos.metadata">
    <package>com.kingdee.eas.wlhlcomm.function.client</package>
    <name>FunctionResource</name>
    <alias>i18nResource[com.kingdee.eas.wlhlcomm.function.client.FunctionResource].alias</alias>
    <description>i18nResource[com.kingdee.eas.wlhlcomm.function.client.FunctionResource].description</description>
    <userDefined>true</userDefined>
    <className>com.kingdee.eas.wlhlcomm.function.client.FunctionResource</className>
    <resourceItems>
        <resourceItem>
            <name>BillUpdateLogQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.wlhlcomm.function.client.FunctionResource].resourceItems.resourceItem[BillUpdateLogQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>TobeUpdateBillsQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.wlhlcomm.function.client.FunctionResource].resourceItems.resourceItem[TobeUpdateBillsQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
    </resourceItems>
    <resource>
        <rs key="i18nResource[com.kingdee.eas.wlhlcomm.function.client.FunctionResource].alias">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.wlhlcomm.function.client.FunctionResource].description">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.wlhlcomm.function.client.FunctionResource].resourceItems.resourceItem[BillUpdateLogQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="单据更新记录" />
            <lang locale="zh_HK" value="單據更新記錄" />
            <lang locale="zh_TW" value="單據更新記錄" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.wlhlcomm.function.client.FunctionResource].resourceItems.resourceItem[TobeUpdateBillsQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="更新单据设置" />
            <lang locale="zh_HK" value="更新單據設置" />
            <lang locale="zh_TW" value="更新單據設置" />
        </rs>
    </resource>
</i18nResource>

