<?xml version="1.0" encoding="UTF-8"?>
<i18nResource xmlns="com.kingdee.bos.metadata">
    <package>com.kingdee.eas.custom.test.client</package>
    <name>TestResource</name>
    <alias>i18nResource[com.kingdee.eas.custom.test.client.TestResource].alias</alias>
    <description>i18nResource[com.kingdee.eas.custom.test.client.TestResource].description</description>
    <userDefined>false</userDefined>
    <className>com.kingdee.eas.custom.test.client.TestResource</className>
    <resourceItems>
        <resourceItem>
            <name>SignwasthetableQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.test.client.TestResource].resourceItems.resourceItem[SignwasthetableQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>VectorQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.test.client.TestResource].resourceItems.resourceItem[VectorQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>VouchertestQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.test.client.TestResource].resourceItems.resourceItem[VouchertestQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>TestQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.test.client.TestResource].resourceItems.resourceItem[TestQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
    </resourceItems>
    <resource>
        <rs key="i18nResource[com.kingdee.eas.custom.test.client.TestResource].alias">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.test.client.TestResource].description">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.test.client.TestResource].resourceItems.resourceItem[SignwasthetableQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="Signwasthetable" />
            <lang locale="zh_HK" value="Signwasthetable" />
            <lang locale="zh_TW" value="Signwasthetable" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.test.client.TestResource].resourceItems.resourceItem[TestQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="测试单据" />
            <lang locale="zh_HK" value="測試單據" />
            <lang locale="zh_TW" value="測試單據" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.test.client.TestResource].resourceItems.resourceItem[VectorQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="Vector" />
            <lang locale="zh_HK" value="Vector" />
            <lang locale="zh_TW" value="Vector" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.test.client.TestResource].resourceItems.resourceItem[VouchertestQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="凭证科目对照表" />
            <lang locale="zh_HK" value="憑證科目對照表" />
            <lang locale="zh_TW" value="憑證科目對照表" />
        </rs>
    </resource>
</i18nResource>

