<?xml version="1.0" encoding="UTF-8"?>
<i18nResource xmlns="com.kingdee.bos.metadata">
    <package>com.kingdee.eas.farm.pig.breedingsow.client</package>
    <name>BreedingsowResource</name>
    <alias>i18nResource[com.kingdee.eas.farm.pig.breedingsow.client.BreedingsowResource].alias</alias>
    <description>i18nResource[com.kingdee.eas.farm.pig.breedingsow.client.BreedingsowResource].description</description>
    <userDefined>true</userDefined>
    <className>com.kingdee.eas.farm.pig.breedingsow.client.BreedingsowResource</className>
    <resourceItems>
        <resourceItem>
            <name>SowQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.pig.breedingsow.client.BreedingsowResource].resourceItems.resourceItem[SowQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>SowPopulationQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.pig.breedingsow.client.BreedingsowResource].resourceItems.resourceItem[SowPopulationQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>SowPolulationQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.pig.breedingsow.client.BreedingsowResource].resourceItems.resourceItem[SowPolulationQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CheckHeatBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.pig.breedingsow.client.BreedingsowResource].resourceItems.resourceItem[CheckHeatBillQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>MatingBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.pig.breedingsow.client.BreedingsowResource].resourceItems.resourceItem[MatingBillQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>GestationCheckQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.pig.breedingsow.client.BreedingsowResource].resourceItems.resourceItem[GestationCheckQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>FetationCheckTypeQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.pig.breedingsow.client.BreedingsowResource].resourceItems.resourceItem[FetationCheckTypeQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>SowAbortionQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.pig.breedingsow.client.BreedingsowResource].resourceItems.resourceItem[SowAbortionQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>DeliveryRecordBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.pig.breedingsow.client.BreedingsowResource].resourceItems.resourceItem[DeliveryRecordBillQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>BabyPigQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.pig.breedingsow.client.BreedingsowResource].resourceItems.resourceItem[BabyPigQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>ReserveSowQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.pig.breedingsow.client.BreedingsowResource].resourceItems.resourceItem[ReserveSowQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>SowRentoutBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.pig.breedingsow.client.BreedingsowResource].resourceItems.resourceItem[SowRentoutBillQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>SowReturnbackBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.pig.breedingsow.client.BreedingsowResource].resourceItems.resourceItem[SowReturnbackBillQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
    </resourceItems>
    <resource>
        <rs key="i18nResource[com.kingdee.eas.farm.pig.breedingsow.client.BreedingsowResource].alias">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.pig.breedingsow.client.BreedingsowResource].description">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.pig.breedingsow.client.BreedingsowResource].resourceItems.resourceItem[BabyPigQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="仔猪建档" />
            <lang locale="zh_HK" value="仔豬建檔" />
            <lang locale="zh_TW" value="仔豬建檔" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.pig.breedingsow.client.BreedingsowResource].resourceItems.resourceItem[CheckHeatBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="查情记录单" />
            <lang locale="zh_HK" value="查情記錄單" />
            <lang locale="zh_TW" value="查情記錄單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.pig.breedingsow.client.BreedingsowResource].resourceItems.resourceItem[DeliveryRecordBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="分娩记录单" />
            <lang locale="zh_HK" value="分娩記錄單" />
            <lang locale="zh_TW" value="分娩記錄單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.pig.breedingsow.client.BreedingsowResource].resourceItems.resourceItem[FetationCheckTypeQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="妊检方式" />
            <lang locale="zh_HK" value="妊檢方式" />
            <lang locale="zh_TW" value="妊檢方式" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.pig.breedingsow.client.BreedingsowResource].resourceItems.resourceItem[GestationCheckQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="母猪妊检记录单" />
            <lang locale="zh_HK" value="母豬妊檢記錄單" />
            <lang locale="zh_TW" value="母豬妊檢記錄單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.pig.breedingsow.client.BreedingsowResource].resourceItems.resourceItem[MatingBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="配种记录单" />
            <lang locale="zh_HK" value="配種記錄單" />
            <lang locale="zh_TW" value="配種記錄單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.pig.breedingsow.client.BreedingsowResource].resourceItems.resourceItem[ReserveSowQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="后备母猪" />
            <lang locale="zh_HK" value="後備母豬" />
            <lang locale="zh_TW" value="後備母豬" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.pig.breedingsow.client.BreedingsowResource].resourceItems.resourceItem[SowAbortionQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="母猪流产记录单" />
            <lang locale="zh_HK" value="母豬流產記錄單" />
            <lang locale="zh_TW" value="母豬流產記錄單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.pig.breedingsow.client.BreedingsowResource].resourceItems.resourceItem[SowPolulationQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="母猪种群" />
            <lang locale="zh_HK" value="母豬種群" />
            <lang locale="zh_TW" value="母豬種群" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.pig.breedingsow.client.BreedingsowResource].resourceItems.resourceItem[SowPopulationQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="母猪种群" />
            <lang locale="zh_HK" value="母豬種群" />
            <lang locale="zh_TW" value="母豬種群" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.pig.breedingsow.client.BreedingsowResource].resourceItems.resourceItem[SowQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="种母猪档案" />
            <lang locale="zh_HK" value="種母豬檔案" />
            <lang locale="zh_TW" value="種母豬檔案" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.pig.breedingsow.client.BreedingsowResource].resourceItems.resourceItem[SowRentoutBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="母猪放养记录" />
            <lang locale="zh_HK" value="母豬放養記錄" />
            <lang locale="zh_TW" value="母豬放養記錄" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.pig.breedingsow.client.BreedingsowResource].resourceItems.resourceItem[SowReturnbackBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="母猪回收记录单" />
            <lang locale="zh_HK" value="母豬回收記錄單" />
            <lang locale="zh_TW" value="母豬回收記錄單" />
        </rs>
    </resource>
</i18nResource>

