<?xml version="1.0" encoding="UTF-8"?>
<i18nResource xmlns="com.kingdee.bos.metadata">
    <package>com.kingdee.eas.custom.dx.weight.client</package>
    <name>WeightResource</name>
    <alias>i18nResource[com.kingdee.eas.custom.dx.weight.client.WeightResource].alias</alias>
    <description>i18nResource[com.kingdee.eas.custom.dx.weight.client.WeightResource].description</description>
    <userDefined>true</userDefined>
    <className>com.kingdee.eas.custom.dx.weight.client.WeightResource</className>
    <resourceItems>
        <resourceItem>
            <name>CarSendBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.dx.weight.client.WeightResource].resourceItems.resourceItem[CarSendBillQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>SettlDetectionQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.dx.weight.client.WeightResource].resourceItems.resourceItem[SettlDetectionQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>SettleBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.dx.weight.client.WeightResource].resourceItems.resourceItem[SettleBillQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>SettleReQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.dx.weight.client.WeightResource].resourceItems.resourceItem[SettleReQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>StandardFrightQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.dx.weight.client.WeightResource].resourceItems.resourceItem[StandardFrightQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>StapleSupplierQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.custom.dx.weight.client.WeightResource].resourceItems.resourceItem[StapleSupplierQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
    </resourceItems>
    <resource>
        <rs key="i18nResource[com.kingdee.eas.custom.dx.weight.client.WeightResource].alias">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.dx.weight.client.WeightResource].description">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.dx.weight.client.WeightResource].resourceItems.resourceItem[CarSendBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="派车单" />
            <lang locale="zh_HK" value="派車單" />
            <lang locale="zh_TW" value="派車單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.dx.weight.client.WeightResource].resourceItems.resourceItem[SettlDetectionQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="结算检测单" />
            <lang locale="zh_HK" value="結算檢測單" />
            <lang locale="zh_TW" value="結算檢測單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.dx.weight.client.WeightResource].resourceItems.resourceItem[SettleBillQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="毛鸡结算单" />
            <lang locale="zh_HK" value="毛雞結算單" />
            <lang locale="zh_TW" value="毛雞結算單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.dx.weight.client.WeightResource].resourceItems.resourceItem[SettleReQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="毛鸡结算检测单" />
            <lang locale="zh_HK" value="毛雞結算檢測單" />
            <lang locale="zh_TW" value="毛雞結算檢測單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.dx.weight.client.WeightResource].resourceItems.resourceItem[StandardFrightQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="标准运费设置" />
            <lang locale="zh_HK" value="標準運費設置" />
            <lang locale="zh_TW" value="標準運費設置" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.custom.dx.weight.client.WeightResource].resourceItems.resourceItem[StapleSupplierQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="原料供应商" />
            <lang locale="zh_HK" value="原料供應商" />
            <lang locale="zh_TW" value="原料供應商" />
        </rs>
    </resource>
</i18nResource>

