<?xml version="1.0" encoding="UTF-8"?>
<i18nResource xmlns="com.kingdee.bos.metadata">
    <package>com.kingdee.eas.farm.pig.client</package>
    <name>PigResource</name>
    <alias>i18nResource[com.kingdee.eas.farm.pig.client.PigResource].alias</alias>
    <description>i18nResource[com.kingdee.eas.farm.pig.client.PigResource].description</description>
    <userDefined>true</userDefined>
    <className>com.kingdee.eas.farm.pig.client.PigResource</className>
    <resourceItems>
        <resourceItem>
            <name>PigFarmQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.pig.client.PigResource].resourceItems.resourceItem[PigFarmQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>PigBatchQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.pig.client.PigResource].resourceItems.resourceItem[PigBatchQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>PigHouseQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.pig.client.PigResource].resourceItems.resourceItem[PigHouseQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CommocialPitBatchQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.pig.client.PigResource].resourceItems.resourceItem[CommocialPitBatchQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>DailyImmunePlanQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.pig.client.PigResource].resourceItems.resourceItem[DailyImmunePlanQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>PigLevelQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.pig.client.PigResource].resourceItems.resourceItem[PigLevelQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>PigFieldQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.pig.client.PigResource].resourceItems.resourceItem[PigFieldQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>PigTypeQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.pig.client.PigResource].resourceItems.resourceItem[PigTypeQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>StrainQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.pig.client.PigResource].resourceItems.resourceItem[StrainQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>PigBatchTypeQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.pig.client.PigResource].resourceItems.resourceItem[PigBatchTypeQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
        <resourceItem>
            <name>PigPolulationQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.farm.pig.client.PigResource].resourceItems.resourceItem[PigPolulationQueryF7WindowTitle].value</value>
            <userDefined>true</userDefined>
        </resourceItem>
    </resourceItems>
    <resource>
        <rs key="i18nResource[com.kingdee.eas.farm.pig.client.PigResource].alias">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.pig.client.PigResource].description">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_HK" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.pig.client.PigResource].resourceItems.resourceItem[CommocialPitBatchQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="商品猪批次" />
            <lang locale="zh_HK" value="商品豬批次" />
            <lang locale="zh_TW" value="商品豬批次" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.pig.client.PigResource].resourceItems.resourceItem[DailyImmunePlanQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="日常免疫计划" />
            <lang locale="zh_HK" value="日常免疫計畫" />
            <lang locale="zh_TW" value="日常免疫計畫" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.pig.client.PigResource].resourceItems.resourceItem[PigBatchQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="猪养殖批次" />
            <lang locale="zh_HK" value="豬養殖批次" />
            <lang locale="zh_TW" value="豬養殖批次" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.pig.client.PigResource].resourceItems.resourceItem[PigBatchTypeQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="猪群分类" />
            <lang locale="zh_HK" value="豬群分類" />
            <lang locale="zh_TW" value="豬群分類" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.pig.client.PigResource].resourceItems.resourceItem[PigFarmQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="养猪场" />
            <lang locale="zh_HK" value="養豬場" />
            <lang locale="zh_TW" value="養豬場" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.pig.client.PigResource].resourceItems.resourceItem[PigFieldQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="栏位" />
            <lang locale="zh_HK" value="欄位" />
            <lang locale="zh_TW" value="欄位" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.pig.client.PigResource].resourceItems.resourceItem[PigHouseQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="猪舍" />
            <lang locale="zh_HK" value="豬舍" />
            <lang locale="zh_TW" value="豬舍" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.pig.client.PigResource].resourceItems.resourceItem[PigLevelQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="猪苗等级" />
            <lang locale="zh_HK" value="豬苗等級" />
            <lang locale="zh_TW" value="豬苗等級" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.pig.client.PigResource].resourceItems.resourceItem[PigPolulationQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="种猪种群" />
            <lang locale="zh_HK" value="種豬種群" />
            <lang locale="zh_TW" value="種豬種群" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.pig.client.PigResource].resourceItems.resourceItem[PigTypeQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="品种" />
            <lang locale="zh_HK" value="品種" />
            <lang locale="zh_TW" value="品種" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.farm.pig.client.PigResource].resourceItems.resourceItem[StrainQueryF7WindowTitle].value">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="品系" />
            <lang locale="zh_HK" value="品系" />
            <lang locale="zh_TW" value="品系" />
        </rs>
    </resource>
</i18nResource>

